module.exports = {
	getGareBelge
};

function getGareBelge(slugare){
	const t1 = "Les gares belges d'autrefois. Guy Demeulder";
	const t2 = "Création et maintenance: contact@garesbelges.be  Mises à jour: oct 2022";
	const base = "https://www.garesbelges.be/";
	const templace = ',"info":"gb:[]"';

	const garesbelgeslist = [
{"href":"brux/anderlecht.htm","desc":"Anderlecht (3 vues)"},
{"href":"brux/arcades.htm","desc":"Arcades (16 vues/1 plan)"},
{"href":"brux/auderghem.htm","desc":"Auderghem (2 vues)"},
{"href":"brux/berchem_sainte_agathe.htm","desc":"Berchem Sainte Agathe (17 vues)"},
{"href":"brux/bockstael.htm","desc":"Bockstael (6 vues)"}, 
{"href":"brux/boitsfort.htm","desc":"Boitsfort I-II (3 vues)"},
{"href":"brux/boitsfort_foret.htm","desc":"Boitsfort Forêt de Soignes"},
{"href":"brux/boondael.htm","desc":"Boondael/Boondaal (6 vues)"},
{"href":"brux/bordet.htm","desc":"Bordet (4 vues)"},
{"href":"brux/bruxelles_allee_verte.htm","desc":"Bruxelles Allée Verte (3 vues)"},
{"href":"brux/bruxelles_bogards.htm","desc":"Bruxelles gare des Bogards (2 vues)"},
{"href":"brux/bruxelles_central.htm","desc":"Bruxelles Central (7 vues)"},
{"href":"brux/bruxelles_chaussee_de_louvain.htm","desc":"Bruxelles Ch de Louvain (3 vues)"},
{"href":"brux/bruxelles_chapelle.htm","desc":"Bruxelles Chapelle"}, 
{"href":"brux/bruxelles_congres.htm","desc":"Bruxelles Congrès (4 vues)"},
{"href":"brux/bruxelles_congres_2019.htm","desc":"Bruxelles Cong. 2019/22 (28 photos)"},
{"href":"brux/bruxelles_midi_I.htm","desc":"Bruxelles Midi I (9 vues)"},
{"href":"brux/bruxelles_midi_II.htm","desc":"Bruxelles Midi II (3 vues - 1 plan)"},
{"href":"brux/bruxelles_midi_III.htm","desc":"Bruxelles Midi III (4 vues)"},
{"href":"brux/bruxelles_nord_I.htm","desc":"Bruxelles Nord I (17 vues/1 plan)"},
{"href":"brux/bruxelles_nord_II.htm","desc":"Bruxelles Nord II (7 vues)"},
{"href":"brux/bruxelles_luxembourg.htm","desc":"Bruxelles Luxembourg I (16 vues)"},
{"href":"brux/bruxelles_luxembourg_II.htm","desc":"Bruxelles Luxembourg II (6 vues)"},
{"href":"brux/bruxelles_ouest.htm","desc":"Bruxelles Ouest (15 vues)"},
{"href":"brux/bruxelles_schuman.htm","desc":"Bruxelles Schuman (6 vues)"},
{"href":"brux/bruxelles_rue_de_la_loi.htm","desc":"Bruxelles rue de la Loi"},
{"href":"brux/cureghem.htm","desc":"Cureghem (2 vues)"},
{"href":"brux/jette.htm","desc":"Jette (13 vues)"},
{"href":"brux/etterbeek.htm","desc":"Etterbeek  I-II-III (20 vues)"},
{"href":"brux/evere.htm","desc":"Evere (7 vues)"},
{"href":"brux/germoir.htm","desc":"Germoir/Mouterij (12 vues)"},
{"href":"brux/haren.htm","desc":"Haren (14 vues)"},
{"href":"brux/haren_sud.htm","desc":"Haren Sud I-II (15 vues)"},
{"href":"brux/koekelberg.htm","desc":"Koekelberg (4 vues)"},
{"href":"brux/laeken.htm","desc":"Laeken (5 vues)"},
{"href":"brux/laeken_halte_royale.htm","desc":"Laeken H.R. (7 vues)"},
{"href":"brux/meiser.htm","desc":"Meiser (21 vues)"},
{"href":"brux/moensberg.htm","desc":"Moensberg (5 vues)"},
{"href":"brux/uccle_calevoet.htm","desc":"Uccle Calevoet (20 vues)"},
{"href":"brux/uccle_stalle.htm","desc":"Uccle Stalle (15 vues)"},
{"href":"brux/forest_midi.htm","desc":"Forest Midi (2 vues)"},
{"href":"brux/forest_est.htm","desc":"Forest Est (14 vues)"},
{"href":"brux/schaerbeek.htm","desc":"Schaerbeek I-II (8 vues + 2 bonus)"},
{"href":"brux/saint_job.htm","desc":"Saint-Job (9 vues)"},
{"href":"brux/simonis.htm","desc":"Simonis (10 vues)"},
{"href":"brux/tour_taxis_I.htm","desc":"Tour et Taxis (march) I (8 vues)"},
{"href":"brux/tour_taxis_I_2019.htm","desc":"Tour et Taxis (march) I en 2019 (23 vues)"},
{"href":"brux/tour_taxis_II.htm","desc":"Tour et Taxis (voy) II (6 vues)"},
{"href":"brux/vivier_d_oie.htm","desc":"Vivier d'Oie/Diesdelle (11 vues)"},
{"href":"brux/watermael.htm","desc":"Watermael (18 vues)"},
{"href":"brux/woluwe_saint_pierre.htm","desc":"Woluwé Saint Pierre (3 vues)"},
{"href":"brux/woluwe_avenue_tervueren.htm","desc":"Woluwé arrêt Av Tervueren (2 vues)"}, 
{"href":"antwerpen_centraal.htm","desc":"Antwerpen Centraal (17 vues)","province":"=================================="},
{"href":"antwerpen_centraal_2012.htm","desc":"Antwerpen Centraal 2012 (11 vues)"},
{"href":"antwerpen_dam.htm","desc":"Antwerpen Dam (25 vues)"},
{"href":"antwerpen_linkeroever.htm","desc":"Antwerpen Linkeroever (10 v/2 p)"},
{"href":"antwerpen_luchtbal.htm","desc":"Antwerpen Luchtbal (15 vues)"}, 
{"href":"antwerpen_noorderdokken.htm","desc":"Antwerpen Noorderdokken (11 vues)"},
{"href":"antwerpen_oost.htm","desc":"Antwerpen Oost I II (6 vues)"},
{"href":"antwerpen_waas.htm","desc":"Antwerpen Waas (2 vues/1 plan)"},
{"href":"antwerpen_zuid.htm","desc":"Antwerpen Zuid I (7 vues-1 plan)"},
{"href":"antwerpen_zuid_II.htm","desc":"Antwerpen Zuid II (6v-2p)"},
{"href":"antwerpen_zurenborg.htm","desc":"Antwerpen Zurenborg Buurtspoorwegen"},
{"href":"balen.htm","desc":"Balen (19 vues)"},
{"href":"berchem.htm","desc":"Berchem II-III (5 vues-2 plans)"},
{"href":"berlaar.htm","desc":"Berlaar (4 vues)"},
{"href":"boechout.htm","desc":"Boechout (7 vues)"},
{"href":"booischot.htm","desc":"Booischot (3 vues)"},
{"href":"boom.htm","desc":"Boom I-II (19 vues)"},
{"href":"bornem.htm","desc":"Bornem I-II (10 vues)"},
{"href":"bouwel.htm","desc":"Bouwel (11 vues)"},
{"href":"brecht.htm","desc":"Brecht Buurtspoorwegen (9 vues)"},
{"href":"duffel.htm","desc":"Duffel I-II-III (8 vues)"},
{"href":"edegem.htm","desc":"Edegem"},
{"href":"ekeren.htm","desc":"Ekeren (21 vues)"},
{"href":"essen.htm","desc":"Essen II-III (10 vues)"},
{"href":"geel.htm","desc":"Geel (5 vues)"},
{"href":"heide.htm","desc":"Heide (8 vues)"},
{"href":"hemiksem.htm","desc":"Hemiksem I-II (12 vues)"},
{"href":"herentals.htm","desc":"Herentals I-II (17 vues)"},
{"href":"heist_op_den_berg.htm","desc":"Heist Op Den Berg I-II (10 vues)"},
{"href":"hoboken_kapellestraat.htm","desc":"Hoboken Kappelestraat"},
{"href":"hoboken_polder.htm","desc":"Hoboken Polder (10 vues)"},
{"href":"hombeek.htm","desc":"Hombeek"},
{"href":"hove.htm","desc":"Hove (9 vues)"}, 
{"href":"hulshout.htm","desc":"Hulshout (2 vues)"}, 
{"href":"kalmthout.htm","desc":"Kalmthout (14 vues)"},
{"href":"kapellen.htm","desc":"Kapellen (11 vues)"},
{"href":"kapellen_militaire.htm","desc":"Kapellen Militair"},
{"href":"kapellenbos.htm","desc":"Kapellenbos"},
{"href":"kessel.htm","desc":"Kessel (10 vues)"},
{"href":"kijkuit.htm","desc":"Kijkuit (8 vues)"},
{"href":"kontich.htm","desc":"Kontich Lint (Contich Kazerne)(6)"},
{"href":"kontich_dorp.htm","desc":"Kontich Dorp (6 vues)"},
{"href":"kontich_nieuwe_lei.htm","desc":"Kontich Nieuwe Lei (+ 2 plans)"},
{"href":"lier.htm","desc":"Lier (7 vues)"},
{"href":"lint.htm","desc":"Lint (2 vues)"},
{"href":"luithagen.htm","desc":"Luithagen (23 vues / 1 plan)"},
{"href":"mechelen_I.htm","desc":"Mechelen I"},
{"href":"mechelen_II.htm","desc":"Mechelen II (9 vues)"},
{"href":"mechelen_III.htm","desc":"Mechelen III (20 vues)"},
{"href":"mechelen_neckerspoel.htm","desc":"Mechelen Nekkerspoel (9)"},
{"href":"mechelen_buurtspoorwegen.htm","desc":"Mechelen Buurtspoorwegen (9)"},
{"href":"meersel_tram_station.htm","desc":"Meesel Buurtspoorwegen (8 vues)"}, 
{"href":"melkouwen.htm","desc":"Melkouwen (3 vues)"},
{"href":"mol.htm","desc":"Mol I-II (13 vues)"},
{"href":"mortsel.htm","desc":"Mortsel (8 vues)"},
{"href":"mortsel_deurnesteenweg.htm","desc":"Mortsel Deurnesteenweg (4 vues)"},
{"href":"mortsel_liersesteenweg.htm","desc":"Mortsel Liersesteenweg (6 vues)"}, 
{"href":"mortsel_oude_god.htm","desc":"Mortsel Oude God II/III/IV (12 vues)"},
{"href":"muizen.htm","desc":"Muizen (12 vues)"}, 
{"href":"niel.htm","desc":"Niel (21 vues)"},
{"href":"nijlen.htm","desc":"Nijlen (4 vues)"},
{"href":"noorderkempen.htm","desc":"Noorderkempen (11 vues)"},  
{"href":"noorderwijk_morkhoven.htm","desc":"Noorderwijk-Morkhoven (7 vues)"}, 
{"href":"olen.htm","desc":"Olen (8 vues)"}, 
{"href":"oorderen.htm","desc":"Oorderen Buurtspoorwegen (2 vues)"},  
{"href":"oppuurs.htm","desc":"Oppuurs (2 vues)"},
{"href":"puurs.htm","desc":"Puurs (22 vues)"}, 
{"href":"puurs_stoomtrein.htm","desc":"Puurs Stoomtrein BVS (10 vues)"}, 
{"href":"reet.htm","desc":"Reet (2 vues)"}, 
{"href":"sauvegarde.htm","desc":"Ruisbroek Sauvegarde I-II (12 vues)"},
{"href":"rumst_buurtspoorwegen.htm","desc":"Rumst Buurtspoorwegen (8 vues)"},
{"href":"schelle.htm","desc":"Schelle I-II (3 vues)"},
{"href":"sint_amands.htm","desc":"Sint-Amands (4 vues)"},
{"href":"sint_katelijne_waver.htm","desc":"Sint Katelijne Waver (18 vues)"},
{"href":"sint_mariaburg.htm","desc":"Sint Mariaburg (11 vues)"},
{"href":"tielen.htm","desc":"Tielen (9 vues)"},
{"href":"turnhout.htm","desc":"Turnhout (14 vues)"},
{"href":"waarloos.htm","desc":"Waarloos (3 vues/2 plans)"},
{"href":"westmeerbeek.htm","desc":"Westmeerbeek (7 vues)"},
{"href":"wildert.htm","desc":"Wildert (7 vues)"},
{"href":"willebroek.htm","desc":"Willebroek I-II (9 vues)"},
{"href":"wilrijk.htm","desc":"Wilrijk (4 vues/1plan)"},
{"href":"wolfstee.htm","desc":"Wolfstee (13 vues)"},
{"href":"zwijndrecht.htm","desc":"Zwijndrecht (8 vues)"},
{"href":"aarschot.htm","desc":"Aarschot I-II (15 vues)","province":"=================================="},
{"href":"asse.htm","desc":"Asse (5 vues)"}, 
{"href":"beersel.htm","desc":"Beersel (5 vues)"}, 
{"href":"beert_bellingen.htm","desc":"Beert Bellingen"}, 
{"href":"begijnendijk.htm","desc":"Begijnendijk (4 vues)"},
{"href":"boortmeerbeek.htm","desc":"Boortmeerbeek (5 vues)"},
{"href":"buda.htm","desc":"[Haren-]Buda (13 vues)"},
{"href":"budingen.htm","desc":"Budingen (4 vues)"},
{"href":"buizingen.htm","desc":"Buizingen (3 vues)"},
{"href":"de_hoek.htm","desc":"De Hoek (3 vues)"},
{"href":"deurne.htm","desc":"Deurne"},
{"href":"diegem.htm","desc":"Diegem I-II (14 vues)"},
{"href":"diest.htm","desc":"Diest I-II (17 vues)"},
{"href":"dilbeek.htm","desc":"Dilbeek  (10 vues)"},
{"href":"dilbeek_buurttramstation.htm","desc":"Dilbeek Buurtspoorwegen (10 vues)"},
{"href":"drieslinter.htm","desc":"Drieslinter"},
{"href":"eppegem.htm","desc":"Eppegem (5 vues)"},
{"href":"erps_kwerps.htm","desc":"Erps Kwerps (14 vues)"},
{"href":"essene_lombeek.htm","desc":"Essene Lombeek (2 vues)"},
{"href":"ezemaal.htm","desc":"Ezemaal I-II (10 vues)"},
{"href":"galmarden.htm","desc":"Galmarden I-II (5 vues)"},
{"href":"geetbets.htm","desc":"Geetbets"},
{"href":"gelrode.htm","desc":"Gelrode (2 vues)"},
{"href":"grimde.htm","desc":"Grimde (5)"},
{"href":"groenendaal.htm","desc":"Groenendaal (13 vues)"},
{"href":"groot_bijgarden.htm","desc":"Groot Bijgarden (6 vues)"},
{"href":"haacht.htm","desc":"Haacht I-II-III (10 vues)"},
{"href":"haacht_buurtspoorwegen.htm","desc":"Haacht Buurtspoorwegen (3 vues)"},
{"href":"halle.htm","desc":"Halle II (10 vues)"},
{"href":"halle_III.htm","desc":"Halle III (24 vues)"},
{"href":"hambos.htm","desc":"Hambos (6 vues)"},
{"href":"haren_noord.htm","desc":"Haren Noord (3 vues)"},
{"href":"herent.htm","desc":"Herent I-II (27 vues)"},
{"href":"herne.htm","desc":"Herne (17 vues)"},
{"href":"hever.htm","desc":"Hever I-II (8 vues)"},
{"href":"heverlee.htm","desc":"Heverlee (13 vues)"},
{"href":"hoegaarden.htm","desc":"Hoegaarden (9 vues)"},
{"href":"hoeilaart.htm","desc":"Hoeilaart (11 vues)"}, 
{"href":"hoeilaart_buurttramstation.htm","desc":"Hoeilaart Buurtspoorwegen (4 vues)"}, 
{"href":"hofstade_strand.htm","desc":"Hofstade [Strand] (8 vues)"}, 
{"href":"holleken.htm","desc":"Holleken (4 vues)"},
{"href":"humbeek_buurttramstation.htm","desc":"Humbeek Buurtspoorwegen (7 vues)"}, 
{"href":"kapelle_op_den_bos.htm","desc":"Kapelle-op-den-Bos (2)"},
{"href":"korbeek_lo.htm","desc":"Korbeek Lo (2 vues)"},
{"href":"kortenberg.htm","desc":"Kortenberg I-II (24 vues)"},
{"href":"kumtich.htm","desc":"Kumtich (3 vues)"},
{"href":"landen.htm","desc":"Landen I-II (13 vues)"},
{"href":"langdorp.htm","desc":"Langdorp (5 vues)"},
{"href":"leerbeek.htm","desc":"Leerbeek Buurtspoorwegen (4 vues)"},
{"href":"lembeek.htm","desc":"Lembeek I-II (8 vues)"},
{"href":"liedekerke.htm","desc":"Liedekerke I-II (9 vues)"},
{"href":"linkebeek.htm","desc":"Linkebeek (9 vues)"},
{"href":"leuven.htm","desc":"Leuven (17 vues/2 plans)"},
{"href":"londerzeel_oost.htm","desc":"Londerzeel Oost (3 vues)"},
{"href":"londerzeel.htm","desc":"Londerzeel [West] (6 vues)"},
{"href":"londerzeel_buurtspoorwegen.htm","desc":"Londerzeel Buurtspoorwegen"}, 
{"href":"lot.htm","desc":"Lot I-II (9 vues)"},
{"href":"lovenjoel.htm","desc":"Lovenjoel (2 vues)"},
{"href":"machelen_brabant.htm","desc":"Machelen-Brabant (12 vues)"},
{"href":"malderen.htm","desc":"Malderen I-II (8 vues)"},
{"href":"merchtem.htm","desc":"Merchtem (7 vues)"}, 
{"href":"neerlinter.htm","desc":"Neerlinter (4 vues)"},
{"href":"neerwinden.htm","desc":"Neerwinden I-II (9 vues)"},
{"href":"nossegem.htm","desc":"Nossegem I-II (19 vues)"},
{"href":"oplinter.htm","desc":"Oplinter (7 vues)"},
{"href":"opwijk.htm","desc":"Opwijk (12 vues)"},
{"href":"oud_heverlee.htm","desc":"Oud Heverlee (11 vues)"},
{"href":"overijse.htm","desc":"Overijse buurtspoorwegen"},
{"href":"racour.htm","desc":"Racour (prov. de Liège)"},
{"href":"roosbeek.htm","desc":"Roosbeek (3 vues)"}, 
{"href":"rotselaar.htm","desc":"Rotselaar (2 vues)"},
{"href":"ruisbroek.htm","desc":"Ruisbroek (12 vues)"},
{"href":"schaffen.htm","desc":"Schaffen (4 vues)"},
{"href":"scherpenheuvel.htm","desc":"Scherpenheuvel (Montaigu)(5 vues)"},
{"href":"sint_genesius_rode.htm","desc":"Sint Genesius Rode (13 vues)"},
{"href":"sint_joris_weert.htm","desc":"St Joris Weert (13 vues)"},
{"href":"sint_joris_weert_tram_station.htm","desc":"St Joris Weert Tram St (12 vues)"},
{"href":"sint_martens_bodegem.htm","desc":"Sint Martens Bodegem (4 vues)"},
{"href":"steenhuffel.htm","desc":"Steenhuffel (4 vues)"},
{"href":"ternat.htm","desc":"Ternat (5 vues)"},
{"href":"tervuren.htm","desc":"Tervuren (5 vues)"},
{"href":"testelt.htm","desc":"Testelt I-II (15 vues)"},
{"href":"tienen.htm","desc":"Tienen (5 vues)"},
{"href":"tienen_2019.htm","desc":"Tienen 2018-2019 (27 vues)"},
{"href":"tienen_tramremises.htm","desc":"Tienen Tramremises (4 vues)"}, 
{"href":"tollembeek.htm","desc":"Tollembeek I-III (8 vues)"},
{"href":"tremelo.htm","desc":"Tremelo Buurtspoorwegen (6 vues)"},
{"href":"veltem.htm","desc":"Veltem I-II (15 vues)"},
{"href":"vertrijk.htm","desc":"Vertrijk I-II (13 vues)"},
{"href":"vilvoorde.htm","desc":"Vilvoorde I-II (23 vues)"},
{"href":"vossem.htm","desc":"Vossem Buurtspoorwegen (3 vues)"}, 
{"href":"waasmont.htm","desc":"Waasmont"}, 
{"href":"weerde.htm","desc":"Weerde (7 vues)"},
{"href":"wespelaar.htm","desc":"Wespelaar I-II (10 vues)"},
{"href":"wezemaal.htm","desc":"Wezemaal (6 vues)"}, 
{"href":"wijgmaal.htm","desc":"Wijgmaal (19 vues)"},
{"href":"wolvertem.htm","desc":"Wolvertem Buurtspoorwegen (3 vues)"},
{"href":"zaventem.htm","desc":"Zaventem (Dorp) I-II (25 vues)"},
{"href":"zichem.htm","desc":"Zichem (27 vues)"},
{"href":"zichem_tramstatie.htm","desc":"Zichem tramstatie (3 vues)"},  
{"href":"zoutleeuw.htm","desc":"Zoutleeuw"},
{"href":"aalbeke.htm","desc":"Aalbeke (3 vues)","province":"=================================="},
{"href":"aarsele.htm","desc":"Aarsele (5 vues)"},
{"href":"abele.htm","desc":"Abele"},
{"href":"adinkerke.htm","desc":"Adinkerke I-II (13 vues)"},
{"href":"anzegem.htm","desc":"Anzegem (4 vues)"},
{"href":"ardooie.htm","desc":"Ardooie (17 vues)"},
{"href":"assebroek.htm","desc":"Assebroek I II (4 vues)"},
{"href":"avelgem.htm","desc":"Avelgem I-II (12 vues)"},
{"href":"beernem.htm","desc":"Beernem I-II (22 vues)"},
{"href":"beitem.htm","desc":"Beitem (4 vues)"},
{"href":"bissegem.htm","desc":"Bissegem"},
{"href":"blankenberge.htm","desc":"Blankenberge I II III (22 vues)"},
{"href":"blankenberge_buurtspoorwegen.htm","desc":"Blankenberge (Buurtspoorwegen)"},
{"href":"boezinge.htm","desc":"Boezinge (4 vues)"},
{"href":"bossuit.htm","desc":"Bossuit (4 vues)"},
{"href":"brugge_I.htm","desc":"Brugge I  (2 vues/1 plan)"},
{"href":"brugge_II.htm","desc":"Brugge II  (7 vues/1 plan)"},
{"href":"brugge_III.htm","desc":"Brugge III (4 vues/1 plan)"},
{"href":"brugge_sint_pieters.htm","desc":"Brugge St Pieters (12 vues/1 plan)"},
{"href":"adinkerke.htm","desc":"[De Panne > voir Adinkerke (8 vues)]"},
{"href":"deerlijk.htm","desc":"Deerlijk (8 vues)"},
{"href":"de_haan.htm","desc":"De Haan (5 vues)"},
{"href":"adinkerke.htm","desc":"De Panne I-II (13 vues)"}, 
{"href":"desselgem.htm","desc":"Desselgem (2 vues)"},
{"href":"diksmuide.htm","desc":"Diksmuide I-II-III (12 vues)"},
{"href":"diksmuide_buurtspoorwegen.htm","desc":"Diksmuide Buurtspoorwegen (2 vues)"}, 
{"href":"duinbergen.htm","desc":"Duinbergen (10 vues)"},
{"href":"eernegem.htm","desc":"Eernegem"},
{"href":"esen.htm","desc":"Esen (4 vues)"},
{"href":"ghistel.htm","desc":"Gistel"},
{"href":"gits.htm","desc":"Gits (10 vues)"},
{"href":"handzame.htm","desc":"Handzame (8 vues)"},
{"href":"harelbeke.htm","desc":"Harelbeke I-II-III (22 vues)"},
{"href":"heirweg.htm","desc":"Heirweg (2 vues)"},
{"href":"heist.htm","desc":"Heist (Knokke Heist) (17 vues)"},
{"href":"ichteghem.htm","desc":"Ichteghem"},
{"href":"ieper.htm","desc":"Ieper I-II-III (22 vues)"},
{"href":"ieper_de_lijn.htm","desc":"Ieper De Lijn (3 vues)"},
{"href":"ingelmunster.htm","desc":"Ingelmunster (9 vues)"},
{"href":"izegem.htm","desc":"Izegem I-II (9 vues)"},
{"href":"jabbeke.htm","desc":"Jabbeke (10 vues)"},
{"href":"kaaskerke.htm","desc":"Kaaskerke"}, 
{"href":"knokke.htm","desc":"Knokke I-II-III (14 vues)"},
{"href":"koksijde.htm","desc":"Koksijde (2 vues)"}, 
{"href":"kooigem.htm","desc":"Kooigem la gare vicinale"},
{"href":"kortekeer.htm","desc":"Kortekeer (4 vues)"},
{"href":"kortemark.htm","desc":"Kortemark I-II (10 vues)"},
{"href":"kortrijk.htm","desc":"Kortrijk II-III (11 vues)"},
{"href":"langemark.htm","desc":"Langemark I-II (17 vues)"},
{"href":"lauwe.htm","desc":"Lauwe (8 vues)"},
{"href":"ledegem.htm","desc":"Ledegem (5 vues)"},
{"href":"lendelede.htm","desc":"Lendelede"},
{"href":"lichtervelde.htm","desc":"Lichtervelde II-III (14 vues)"},
{"href":"lissewege.htm","desc":"Lissewege II (9 vues)"},
{"href":"marke.htm","desc":"Marke(2 vues)"},
{"href":"menen.htm","desc":"Menen I-II-III (12 vues)"},
{"href":"meulebeke.htm","desc":"Meulebeke (16 vues)"},
{"href":"moen_heestert.htm","desc":"Moen Heestert (6 vues)"},
{"href":"moere.htm","desc":"Moere (12 vues)"},
{"href":"moorslede.htm","desc":"Moorslede Passendale I-II (4 vues)"},
{"href":"nieuwpoort_bad.htm","desc":"Nieuwpoort Bad (4 vues)"},
{"href":"nieuwpoort_stad.htm","desc":"Nieuwpoort Stad (7 vues)"},
{"href":"oostkerke.htm","desc":"Oostkerke (5 vues)"},
{"href":"oostrozebeke.htm","desc":"Oostrozebeke (18 vues)"},
{"href":"oostende_kaai.htm","desc":"Oostende Kaai (12 vues/1 plan)"},
{"href":"oostende_2019.htm","desc":"Oostende 2019 (11 photos)"},
{"href":"oostende_delijn_2019.htm","desc":"Oostende De Lijn 2019 (9 photos)"},
{"href":"oostende_2_stations.htm","desc":"Oostende les 2 gares"},
{"href":"oostende_stad.htm","desc":"Oostende Stad I-II(9 vues/1 plan)"},
{"href":"oostkamp.htm","desc":"Oostkamp (30 vues)"},
{"href":"oostnieuwkerke.htm","desc":"Oostnieuwkerke (5 vues)"},
{"href":"oudenburg.htm","desc":"Oudenburg (5 vues)"},
{"href":"pervijze.htm","desc":"Pervijze (7 vues)"},
{"href":"pittem.htm","desc":"Pittem (3 vues)"},
{"href":"poelkapelle.htm","desc":"Poelkapelle I-II (3 vues)"},
{"href":"poperinge.htm","desc":"Poperinge (16 vues)"},
{"href":"roeselaere.htm","desc":"Roeselaere I-II (39 vues)"}, 
{"href":"rumbeke.htm","desc":"Rumbeke"},{"href":"sijsele.htm","desc":"Sijsele (2 vues)"},
{"href":"sint_denijs_helkijn.htm","desc":"Sint-Denijs-Helkijn (2 vues)"},
{"href":"sint_eloois_vijve.htm","desc":"Sint Eloois Vijve (6 vues)"},  
{"href":"sint_jozef.htm","desc":"Sint Jozef (13 vues)"},
{"href":"sint_michiels.htm","desc":"Sint Michiels"},
{"href":"spiere.htm","desc":"Spiere (4 vues)"}, 
{"href":"staden.htm","desc":"Staden (25 vues)"},
{"href":"stasegem.htm","desc":"Stasegem (2 vues)"},
{"href":"steenbrugge.htm","desc":"Steenbrugge (4 vues)"},
{"href":"tielt.htm","desc":"Tielt I-II (4 vues)"},
{"href":"torhout.htm","desc":"Torhout I-II-III (11 vues)"},
{"href":"varsenare.htm","desc":"Varsenare (10 vues)"},
{"href":"veurne.htm","desc":"Veurne (17 vues)"},
{"href":"vichte.htm","desc":"Vichte (11 vues)"},
{"href":"vlamertinge.htm","desc":"Vlamertinge I-II (12 vues)"},
{"href":"waregem.htm","desc":"Waregem I-II (5 vues)"},
{"href":"wenduine.htm","desc":"Wenduine buurtspoorwegen (3 vues)"}, 
{"href":"wervik.htm","desc":"Wervik I-II (7 vues)"},
{"href":"westende.htm","desc":"Westende buurtspoorwegen"},  
{"href":"westrozebeke.htm","desc":"Westrozebeke (6 vues)"},
{"href":"westvleteren.htm","desc":"Westvleteren Buurtspoorwegen"}, 
{"href":"wevelgem.htm","desc":"Wevelgem (13 vues)"},
{"href":"wielsbeke.htm","desc":"Wielsbeke (2 vues)"},
{"href":"wynendaele.htm","desc":"Wynendaele (2 vues)"},
{"href":"zandvoorde.htm","desc":"Zandvoorde (2 vues)"},
{"href":"zarren.htm","desc":"Zarren I-II (7 vues)"},
{"href":"zedelgem.htm","desc":"Zedelgem (12 vues)"}, 
{"href":"zeebrugge.htm","desc":"Zeebrugge Dorp I-II-III (21v/1p)"},
{"href":"zeebrugge_ferry.htm","desc":"Zeebrugge Ferry (5 vues))"}, 
{"href":"zeebrugge_strand.htm","desc":"Zeebrugge Strand (18v/1p)"},
{"href":"zillebeke.htm","desc":"Zillebeke (2 vues)"},
{"href":"zonnebeke.htm","desc":"Zonnebeke"},
{"href":"zuienkerke.htm","desc":"Zuienkerke (= Lissewege I)"},
{"href":"zwankendamme.htm","desc":"Zwankendamme (3 vues)"},
{"href":"zwevegem.htm","desc":"Zwevegem"}, 
{"href":"aalst.htm","desc":"Aalst (8 vues)","province":"=================================="}, 
{"href":"aalst_kerrebroek.htm","desc":"Aalst-Kerrebroek (5 vues)"}, 
{"href":"aalter.htm","desc":"Aalter I-II (17 vues)"},
{"href":"adegem.htm","desc":"Adegem (2 vues)"},
{"href":"appelterre.htm","desc":"Appelterre (5 vues)"},
{"href":"baardegem.htm","desc":"Baardegem (4 vues)"},
{"href":"baasrode_noord.htm","desc":"Baasrode Noord I-II (17 vues)"},
{"href":"baasrode_zuid.htm","desc":"Baasrode Zuid (4 vues)"},
{"href":"balegem.htm","desc":"Balegem"},
{"href":"balegem_dorp.htm","desc":"Balegem Dorp (7 vues)"},
{"href":"bambrugge.htm","desc":"Bambrugge (11 vues)"},
{"href":"bassevelde.htm","desc":"Bassevelde (2 vues)"},
{"href":"beervelde.htm","desc":"Beervelde (8vues)"},
{"href":"bellem.htm","desc":"Bellem I-II (20 vues)"},
{"href":"belsele.htm","desc":"Belsele I-II (4 vues)"},
{"href":"berchem_oost_vlaanderen.htm","desc":"Berchem (Oost Vl.) (2 vues)"},  
{"href":"beveren.htm","desc":"Beveren (Waas) (7 vues)"},
{"href":"boekhoute.htm","desc":"Boekhoute (3 vues)"},
{"href":"buggenhout.htm","desc":"Buggenhout I-II-III (7 vues)"}, 
{"href":"burst.htm","desc":"Burst I-II (6 vues)"},
{"href":"daknam.htm","desc":"Daknam (6 vues)"}, 
{"href":"deinze.htm","desc":"Deinze I-II-III (15 vues)"},
{"href":"de_klinge.htm","desc":"De Klinge (7 vues)"},
{"href":"denderleeuw.htm","desc":"Denderleeuw I-II (6 vues)"},
{"href":"dendermonde.htm","desc":"Dendermonde I-II (8 vues)"},
{"href":"de_pinte.htm","desc":"De Pinte I-II (11 vues)"},
{"href":"donk.htm","desc":"Donk (3 vues)"},  
{"href":"drongen.htm","desc":"Drongen I-II-III (10 vues)"},
{"href":"ede.htm","desc":"Ede (6 vues)"}, 
{"href":"eeklo.htm","desc":"Eeklo I II (2 vues)"},
{"href":"eichem.htm","desc":"Eichem (7 vues)"}, 
{"href":"eine.htm","desc":"Eine (5 vues)"},
{"href":"eke_nazareth.htm","desc":"Eke-Nazareth (4 vues)"}, 
{"href":"eksaarde.htm","desc":"Eksaarde (8 vues)"}, 
{"href":"ename.htm","desc":"Ename"},
{"href":"erembodegem.htm","desc":"Erembodegem (7 vues)"},
{"href":"erpe_mere.htm","desc":"Erpe-Mere I-II (7 vues)"},
{"href":"ertvelde.htm","desc":"Ertvelde (12 vues)"},
{"href":"erwetegem.htm","desc":"Erwetegem"}, 
{"href":"etikhove.htm","desc":"Etikhove (5 vues)"},
{"href":"evergem.htm","desc":"Evergem I-II (13 vues)"},
{"href":"evergem_de_lijn.htm","desc":"Evergem De Lijn (4 vues)"},
{"href":"gavere.htm","desc":"Gavere (2 vues)"},
{"href":"gent_dampoort.htm","desc":"Gent Dampoort (19 vues)"},
{"href":"gent_sint_pieters.htm","desc":"Gent-St-Pieters I-II (20 vues/4 plans)"},
{"href":"gent_waas.htm","desc":"Gent Waas (2 vues)"},
{"href":"gent_zuid.htm","desc":"Gent Zuid (7 vues/2 plans)"},
{"href":"gentbrugge.htm","desc":"Gentbrugge (13 vues)"},
{"href":"gentbrugge_noord.htm","desc":"Gentbrugge Noord"},
{"href":"geraardsbergen.htm","desc":"Geraardsbergen I-II (4 vues)"},
{"href":"gijzegem.htm","desc":"Gijzegem (3 vues)"},
{"href":"gontrode.htm","desc":"Gontrode (12 vues)"},
{"href":"grammene.htm","desc":"Grammene (2 vues)"},
{"href":"grembergen.htm","desc":"Grembergen (2 vues)"},
{"href":"haaltert.htm","desc":"Haaltert (8 vues)"},
{"href":"hamme.htm","desc":"Hamme (5 vues)"},
{"href":"hansbeke.htm","desc":"Hansbeke I-II-III (23 vues)"},
{"href":"heiken.htm","desc":"Heiken"},
{"href":"heizijde.htm","desc":"Heizijde (6 vues)"},
{"href":"herzele.htm","desc":"Herzele (17 vues)"},
{"href":"herzele_tram.htm","desc":"Herzele NMVB (6 vues)"},
{"href":"hillegem.htm","desc":"Hillegem (8 vues)"},
{"href":"hofstade.htm","desc":"Hofstade"},
{"href":"huivelde.htm","desc":"Huivelde (3 vues)"}, 
{"href":"idegem.htm","desc":"Idegem (7 vues)"},
{"href":"kaprijke.htm","desc":"Kaprijke (3 vues)"},
{"href":"kemzeke.htm","desc":"Kemzeke (3 vues)"},
{"href":"klein_sinaai.htm","desc":"Klein-Sinaai (6 vues)"},
{"href":"kwatrecht.htm","desc":"Kwatrecht (9 vues)"},
{"href":"landegem.htm","desc":"Landegem (18 vues)"},
{"href":"landskouter.htm","desc":"Landskouter (9 vues)"},
{"href":"langerbrugge.htm","desc":"Langerbrugge (14 vues)"},
{"href":"lebbeke.htm","desc":"Lebbeke (6 vues)"},
{"href":"lede.htm","desc":"Lede I-II (8 vues)"},
{"href":"leupegem.htm","desc":"Leupegem (5 vues)"},
{"href":"lierde.htm","desc":"[Sint Maria] Lierde (24 vues)"},
{"href":"lochristi.htm","desc":"Lochristi (2 vues)"},
{"href":"lokeren.htm","desc":"Lokeren (8 vues)"},
{"href":"louise_marie.htm","desc":"Louise-Marie"},
{"href":"machelen.htm","desc":"Machelen (2 vues)"}, 
{"href":"maldegem.htm","desc":"Maldegem (6 vues)"},
{"href":"maria_aalter.htm","desc":"Maria-Aalter (16 vues)"},
{"href":"melden.htm","desc":"Melden (2 vues)"},
{"href":"melle.htm","desc":"Melle (11 vues)"},
{"href":"melsele.htm","desc":"Melsele I-II  (7 vues)"},
{"href":"merelbeke.htm","desc":"Merelbeke I-II (19 vues)"},
{"href":"michelbeke.htm","desc":"Michelbeke (3 vues)"},
{"href":"middelburg.htm","desc":"Middelburg buurtspoorwegen"},
{"href":"moerbeke_waas.htm","desc":"Moerbeke Waas (12 vues)"},
{"href":"moortsele.htm","desc":"Moortsele I-II  (9 vues)"},
{"href":"munkzwalm.htm","desc":"Munkzwalm (4 vues)"},
{"href":"nederbrakel.htm","desc":"Nederbrakel (3 vues)"},
{"href":"nieuwkerken.htm","desc":"Nieuwkerken Waas I-II (7 vues)"},
{"href":"ninove.htm","desc":"Ninove (3 vues)"},
{"href":"okegem.htm","desc":"Okegem (10 vues)"},
{"href":"olsene.htm","desc":"Olsene (2 vues)"},
{"href":"oostackker.htm","desc":"Oostakker (7 vues)"},
{"href":"opbrakel.htm","desc":"Opbrakel (3 vues)"},
{"href":"oudegem.htm","desc":"Oudegem I-II (8 vues)"},
{"href":"oudenaarde.htm","desc":"Oudenaarde I (14 vues)"},
{"href":"petegem.htm","desc":"Petegem (2 vues)"},
{"href":"roborst.htm","desc":"Roborst"},
{"href":"ronse.htm","desc":"Ronse I/II (15 vues)"},
{"href":"ruien.htm","desc":"Ruien I-II (10 vues)"},
{"href":"scheldewindeke.htm","desc":"Scheldewindeke (9 vues)"},
{"href":"schellebelle.htm","desc":"Schellebelle I-II (3 vues)"},
{"href":"schendelbeke.htm","desc":"Schendelbeke (6 vues)"},
{"href":"schoonaarde.htm","desc":"Schoonaarde (10 vues)"},
{"href":"serskamp.htm","desc":"Serskamp (6 vues)"},
{"href":"sinaai.htm","desc":"Sinaai (Duizend Appels)(11 vues)"},
{"href":"sint_denijs_boekel.htm","desc":"Sint-Denijs-Boekel-[Nederzwalm] (12 vues)"},
{"href":"sint_denijs_westrem.htm","desc":"Sint-Denijs-Westrem (9 vues)"},
{"href":"sint_gillis_waas.htm","desc":"Sint-Gillis-Waas (9 vues)"},
{"href":"sint_lievens_esse_tram.htm","desc":"Sint Lievens Esse NMVB(4 vues)"}, 
{"href":"lierde.htm","desc":"Sint Maria Lierde > Lierde"},
{"href":"sint_niklaas.htm","desc":"Sint Niklaas I-II (Waes)(10 vues)"},
{"href":"sint_niklaas_west.htm","desc":"Sint Niklaas West (2 vues)"}, 
{"href":"sleidinge.htm","desc":"Sleidinge (10 vues)"},
{"href":"stekene.htm","desc":"Stekene (9 vues)"},
{"href":"temse.htm","desc":"Temse I-II (16 vues)"},
{"href":"terdonk.htm","desc":"Terdonk (2 vues)"},
{"href":"terhagen.htm","desc":"Terhagen (12 vues)"},
{"href":"viane_moerbeke.htm","desc":"Viane Moerbeke (10 vues)"},
{"href":"vijfhuizen.htm","desc":"Vijfhuizen (8 vues)"},
{"href":"waarschoot.htm","desc":"Waarschoot (11 vues)"},
{"href":"waasmunster.htm","desc":"Waasmunster (2 vues)"},
{"href":"wachtebeke.htm","desc":"Wachtebeke (8 vues)"},
{"href":"welle.htm","desc":"Welle (5 vues)"},
{"href":"wetteren.htm","desc":"Wetteren (12 vues)"},
{"href":"wichelen.htm","desc":"Wichelen I-II (8 vues)"},
{"href":"wondelgem.htm","desc":"Wondelgem (8 vues)"},
{"href":"zandbergen.htm","desc":"Zandbergen (9 vues)"},
{"href":"zele.htm","desc":"Zele (3 vues)"},
{"href":"zelzate.htm","desc":"Zelzate I-II (5 vues)"},
{"href":"zeveneken.htm","desc":"Zeveneken Oudenbos (2 vues)"},
{"href":"zingem.htm","desc":"Zingem II (8 vues)"}, 
{"href":"zottegem.htm","desc":"Zottegem I-II (6 vues)"},
{"href":"zulte.htm","desc":"Zulte (2 vues)"},
{"href":"achel.htm","desc":"Achel (3 vues)","province":"=================================="},
{"href":"alken.htm","desc":"Alken (7 vues)"},
{"href":"as.htm","desc":"As (22 vues)"},
{"href":"beringen.htm","desc":"Beringen (19 vues)"},
{"href":"beringen_mijnen.htm","desc":"Beringen Mijnen (2 vues)"},
{"href":"bernissem.htm","desc":"Bernissem"},
{"href":"beverlo.htm","desc":"Beverlo (5 vues)"},
{"href":"beverst.htm","desc":"Beverst"},
{"href":"bilzen.htm","desc":"Bilzen (8 vues)"},
{"href":"bokrijk.htm","desc":"Bokrijk (9 vues)"},
{"href":"borgloon.htm","desc":"Borgloon (5 vues)"},
{"href":"diepenbeek.htm","desc":"Diepenbeek (5 vues)"},
{"href":"eigenbilzen.htm","desc":"Eigenbilzen (2 vues)"},
{"href":"elen.htm","desc":"Elen (2 vues)"},
{"href":"eisden.htm","desc":"Eisden (16 vues)"},
{"href":"exel.htm","desc":"Exel"},
{"href":"genk.htm","desc":"Genk I-II (19 vues/1 plan)"},
{"href":"gingelom.htm","desc":"Gingelom (2 vues)"},
{"href":"halen.htm","desc":"Halen (2 vues)"},
{"href":"hamont.htm","desc":"Hamont I-II (23 vues)"},
{"href":"hasselt.htm","desc":"Hasselt II-III (8 vues)"},
{"href":"helchteren.htm","desc":"Helchteren"},
{"href":"heppen.htm","desc":"Heppen (4 vues)"},
{"href":"heusden.htm","desc":"Heusden (6 vues)"},
{"href":"hoepertingen.htm","desc":"Hoepertingen (2 vues)"},
{"href":"hoeselt.htm","desc":"Hoeselt (2 vues)"},
{"href":"jesseren.htm","desc":"Jesseren (9 vues)"},
{"href":"jeuk.htm","desc":"Jeuk Rosoux (2 vues)"}, 
{"href":"kermt.htm","desc":"Kermt (3 vues)"},
{"href":"kerniel.htm","desc":"Kerniel (7 vues)"},
{"href":"kiewit.htm","desc":"Kiewit (11 vues)"},
{"href":"kortenbos.htm","desc":"Kortenbos (2 vues)"},
{"href":"lanaken.htm","desc":"Lanaken (3 vues)"},
{"href":"leopoldsburg.htm","desc":"Leopoldsburg (24 vues)"},
{"href":"leopoldsburg_2022.htm","desc":"Leopoldsburg en 2022 (12))"},
{"href":"lommel.htm","desc":"Lommel I-II (17 vues)"},
{"href":"maaseik.htm","desc":"Maaseik I-II (2 vues)"},
{"href":"melveren.htm","desc":"Melveren"},
{"href":"munsterbilzen.htm","desc":"Munsterbilzen (2 vues)"},
{"href":"nerem.htm","desc":"Nerem"},
{"href":"neerpelt.htm","desc":"Neerpelt (33 vues)"},
{"href":"ordingen.htm","desc":"Ordingen"},
{"href":"overpelt.htm","desc":"Overpelt (9 vues)"},
{"href":"overpelt-Werkplaatsen.htm","desc":"Overpelt Werkplaatsen"}, 
{"href":"piringen.htm","desc":"Piringen (9 vues)"},
{"href":"remersdaal.htm","desc":"Remersdaal (block) (3 vues)"},
{"href":"schulen.htm","desc":"Schulen I-II "},
{"href":"sint_huibrechts_lille.htm","desc":"Sint-Huibrechts-Lille (2)"},
{"href":"sint_martens_voeren.htm","desc":"Sint-Martens-Voeren"},
{"href":"sint_truiden.htm","desc":"Sint Truiden I-II (9 vues)"},
{"href":"tessenderlo.htm","desc":"Tessenderlo (4 vues)"},
{"href":"tongeren.htm","desc":"Tongeren I-II (18 vues)"},
{"href":"velm.htm","desc":"Velm"},
{"href":"waterschei.htm","desc":"Waterschei (10 vues)"},
{"href":"wijchmaal.htm","desc":"Wijchmaal (2 vues)"},
{"href":"wilderen.htm","desc":"Wilderen (22 vues)"},
{"href":"winterslag.htm","desc":"Winterslag (2 vues)"},
{"href":"zelem.htm","desc":"Zelem"},
{"href":"zolder.htm","desc":"Zolder (12 vues)"},
{"href":"zonhoven.htm","desc":"Zonhoven (7 vues)"},
{"href":"zwartberg.htm","desc":"Zwartberg / Genk Goed. (8 vues)"}, 
{"href":"agimont.htm","desc":"Agimont (7 vues)","province":"=================================="},
{"href":"aisemont.htm","desc":"Aisemont (2 vues)"},
{"href":"alle_sur_semois.htm","desc":"Alle sur Semois (11 vues)"},
{"href":"andenne.htm","desc":"Andenne I-II (11 vues)"},
{"href":"anhee.htm","desc":"Anhée I-II (6 vues)"},
{"href":"anseremme.htm","desc":"Anseremme (21 vues)"}, 
{"href":"assesse.htm","desc":"Assesse (10 vues)"},
{"href":"aublain.htm","desc":"Aublain (7 vues)"},
{"href":"auvelais.htm","desc":"Auvelais I-II (13 vues)"},
{"href":"bambois.htm","desc":"Bambois (13 vues)"},
{"href":"bauche.htm","desc":"Bauche PN 6 (8 vues)"},
{"href":"beauraing.htm","desc":"Beauraing (15 vues)"},
{"href":"beez.htm","desc":"Beez (3 vues)"},
{"href":"berzee.htm","desc":"Berzée (26 vues)"},
{"href":"beuzet.htm","desc":"Beuzet I-II (6 vues)"},
{"href":"biesmes.htm","desc":"Biesme(s)(9 vues)"},
{"href":"biesmeree.htm","desc":"Biesmerée (10 vues)"},
{"href":"bormenville.htm","desc":"Bormenville (8 vues/1 plan)"},
{"href":"boussu_en_fagne.htm","desc":"Boussu en Fagne(s) (16 vues)"},
{"href":"bouvignes.htm","desc":"Bouvignes sur Meuse"},
{"href":"braibant.htm","desc":"Braibant (4 vues)"},
{"href":"cerfontaine.htm","desc":"Cerfontaine I-II (7 vues/2 plans)"},
{"href":"chapelle_dieu.htm","desc":"Chapelle Dieu (14 vues)"},
{"href":"chapois.htm","desc":"Chapois (7 vues)"},
{"href":"chateau_de_seilles.htm","desc":"Château de Seilles (10 vues)"},
{"href":"ciney_I.htm","desc":"Ciney I (2 vues)"},
{"href":"ciney_II.htm","desc":"Ciney II (7 vues)"},
{"href":"ciney_III.htm","desc":"Ciney III (11 vues)"}, 
{"href":"cognelee.htm","desc":"Cognelée (3 vues)"},
{"href":"corroy_le_chateau.htm","desc":"Corroy-le-Château"}, 
{"href":"courriere.htm","desc":"Courrière (6 vues)"},
{"href":"couvin.htm","desc":"Couvin (14 vues)"},
{"href":"cul_des_sarts.htm","desc":"Cul Des Sarts (2 vues)"},
{"href":"dave_etat.htm","desc":"Dave Etat = Dave St Martin (16)"},
{"href":"dave.htm","desc":"Dave Nord (5 vues)"},
{"href":"denee.htm","desc":"Denée Maredsous (8 vues)"},
{"href":"dinant.htm","desc":"Dinant I-II (24 vues)"},
{"href":"doische.htm","desc":"Doische (8 vues)"},
{"href":"dorinne.htm","desc":"Dorinne Durnal (8 vues)"},
{"href":"eghezee.htm","desc":"Eghezée (3 vues)"},
{"href":"emptinne.htm","desc":"Emptinne (3 vues)"},
{"href":"eprave.htm","desc":"Eprave (6 vues)"},
{"href":"ermeton.htm","desc":"Ermeton sur Biert (13 v)"},
{"href":"ernage.htm","desc":"Ernage I-II (5 vues)"},
{"href":"evrehailles.htm","desc":"Evrehailles Bauche (22 vues)"},
{"href":"fagnolle.htm","desc":"Fagnolle"},
{"href":"falaen.htm","desc":"FalÃ¤en (5 vues)"},
{"href":"falemprise.htm","desc":"Falemprise I-II (3 vues/1 plan)"},
{"href":"falisolle.htm","desc":"Falisolle (19 vues)"},
{"href":"flawinne.htm","desc":"Flawinne (11 vues)"},
{"href":"floree.htm","desc":"Florée"},
{"href":"floreffe.htm","desc":"Floreffe (18 vues)"},
{"href":"florennes.htm","desc":"Florennes Central (4 vues/1 plan)"},
{"href":"florennes_est.htm","desc":"Florennes Est (3 vues/1 plan)"},
{"href":"florennes_pavillon.htm","desc":"Florennes Pavillon (6 vues/1 plan)"},
{"href":"florennes_sud.htm","desc":"Florennes Sud (3 vues/1 plan)"},
{"href":"forville.htm","desc":"Forville (vicinale)"},
{"href":"fosses_la_ville.htm","desc":"Fosses [La Ville] (24 vues)"},
{"href":"fosses_la_ville_vicinal.htm","desc":"Fosses La Ville vicinal (5 vues)"},
{"href":"fraire.htm","desc":"Fraire (9 vues/2 plans)"},
{"href":"fraire_humide.htm","desc":"Fraire Humide (9 vues/1 plan)"}, 
{"href":"franiere.htm","desc":"Franière (14 vues)"},
{"href":"frasnes_lez_couvin.htm","desc":"Frasnes-lez-Couvin (8 vues)"},
{"href":"froidmont_namur.htm","desc":"Froidmont (9 vues/1 plan)"},
{"href":"furnaux.htm","desc":"Furnaux (7 vues)"}, 
{"href":"gedinne.htm","desc":"Gedinne (17 vues)"},
{"href":"gembloux.htm","desc":"Gembloux I-II (16 vues)"},
{"href":"gendron_celles.htm","desc":"Gendron Celles (15 vues)"},
{"href":"gerlimpont.htm","desc":"Gerlimpont (3 vues)"}, 
{"href":"gimnee.htm","desc":"Gimnée"},
{"href":"godinne.htm","desc":"Godinne (15 vues)"},
{"href":"graide.htm","desc":"Graide (11 vues)"},
{"href":"halloy.htm","desc":"Halloy (3 vues)"},
{"href":"halte_royale_d_ardenne.htm","desc":"Halte Royale d'Ardenne (11 vues)"},
{"href":"ham_sur_sambre.htm","desc":"Ham sur Sambre (8 vues)"},
{"href":"hamois.htm","desc":"Hamois (14 vues/1 plan)"},
{"href":"hanzinne.htm","desc":"Hanzinne (4 vues)"},
{"href":"hastiere.htm","desc":"Hastière (9 vues)"},
{"href":"havelange.htm","desc":"Havelange (8 vues/1 plan)"},
{"href":"haversin.htm","desc":"Haversin (10 vues)"},
{"href":"heer_agimont.htm","desc":"Heer Agimont (11 vues)"},
{"href":"hemptinne.htm","desc":"Hemptinne (5 vues)"},
{"href":"hermeton.htm","desc":"Hermeton"},
{"href":"hogne.htm","desc":"Hogne (10 vues)"},
{"href":"hour_havenne.htm","desc":"Hour Havenne (6 vues)"},
{"href":"houyet.htm","desc":"Houyet (29 vues/4 plans)"},
{"href":"houyet_vicinal.htm","desc":"Houyet vicinal"}, 
{"href":"jambes_etat.htm","desc":"Jambes Etat = Jambes Est (7)"},
{"href":"jambes_nord.htm","desc":"Jambes Nord (13 vues)"},
{"href":"jemelle.htm","desc":"Jemelle - Rochefort I-II-III (19 vues)"},
{"href":"jemeppe_sur_sambre.htm","desc":"Jemeppe Sur Sambre (20 vues)"},
{"href":"jemeppe_froidmont.htm","desc":"Jemeppe Froidmont"},
{"href":"laneffe.htm","desc":"Laneffe"},
{"href":"leignon.htm","desc":"Leignon (11 vues)"},
{"href":"lesves_vicinal.htm","desc":"Lesves Gare vicinale."},
{"href":"leuze_longchamps.htm","desc":"Leuze Longchamps (4 vues)"},
{"href":"liennes.htm","desc":"Liennes (2 vues)."},
{"href":"ligny.htm","desc":"Ligny (carrières)(10 vues)"},
{"href":"ligny_sud.htm","desc":"Ligny (sud) (2 vues)"},
{"href":"lonzee.htm","desc":"Lonzée I-II (8 vues)"},
{"href":"lustin.htm","desc":"Lustin I-II (13 vues)"},
{"href":"marche_les_dames.htm","desc":"Marche les Dames (14 vues)"},
{"href":"maredret.htm","desc":"Maredret (9 vues)"},
{"href":"mariembourg.htm","desc":"Mariembourg (10 vues)"},
{"href":"martouzin.htm","desc":"Martouzin (11 vues)"},
{"href":"matagne_la_grande.htm","desc":"Matagne la Grande (4 vues)"},
{"href":"matagne_la_petite.htm","desc":"Matagne la Petite"}, 
{"href":"mazy.htm","desc":"Mazy (20 vues)"},
{"href":"mettet.htm","desc":"Mettet (3 vues)"}, 
{"href":"merlemont.htm","desc":"Merlemont (3 vues)"},
{"href":"moignelee.htm","desc":"Moignelée"},
{"href":"moustier.htm","desc":"Moustier (S Sambre) (21 vues)"},
{"href":"morialme.htm","desc":"Morialmé (14 vues/1 plan)"},
{"href":"morialme_minieres.htm","desc":"Morialmé Minières (6 vues/1 plan)"},
{"href":"nameche.htm","desc":"Namêche (7 vues)"},
{"href":"namur.htm","desc":"Namur (11 vues)"},
{"href":"namur_2017.htm","desc":"Namur en 2017 (6 vues)"},
{"href":"naninne.htm","desc":"Naninne (7 vues)"},
{"href":"natoye.htm","desc":"Natoye (8 vues)"},
{"href":"neuville.htm","desc":"Neuville(Nord) (7 vues)"}, 
{"href":"nismes.htm","desc":"Nismes (5 vues)"},  
{"href":"novilles_taviers.htm","desc":"Novilles Taviers (3 vues)"},
{"href":"ohey.htm","desc":"Ohey Gare vicinale (8 vues)"},
{"href":"olloy.htm","desc":"Olloy sur Viroin (7 vues)"},
{"href":"petit_avin.htm","desc":"Petit Avin (3 vues/1 plan)"},
{"href":"petite_chapelle.htm","desc":"Petite Chapelle (4 vues)"},
{"href":"philippeville1.htm","desc":"Philippeville I (1 vues/2 plans)"},
{"href":"philippeville.htm","desc":"Philippeville II (15 vues/2 plans)"},
{"href":"pondrome.htm","desc":"PondrÃ´me (5 vues)"},
{"href":"pry.htm","desc":"Pry (11 vues)"}, 
{"href":"purnode.htm","desc":"Purnode (5 vues)"},
{"href":"pussemange.htm","desc":"Pussemange (vicinale, 5 vues)"},
{"href":"rhisnes.htm","desc":"Rhisnes (17 vues)"},
{"href":"rochefort.htm","desc":"Rochefort (22 vues)"},
{"href":"romedenne.htm","desc":"Romedenne Surice (7 vues)"},
{"href":"romeree.htm","desc":"Romerée (3 vues)"},
{"href":"ronet.htm","desc":"Ronet (8 vues)"},
{"href":"saint_aubin.htm","desc":"Saint Aubin (6 vues/1 plan)"},
{"href":"saint_denis_bovesse.htm","desc":"Saint-Denis-Bovesse (20 vues)"},
{"href":"saint_gerard.htm","desc":"Saint Gérard (16 vues)"},
{"href":"saint_lambert.htm","desc":"Saint Lambert (16 vues)"},
{"href":"saint_servais.htm","desc":"Saint Servais (6 vues)"},
{"href":"sart_bernard.htm","desc":"Sart Bernard (4 vues)"}, 
{"href":"sauveniere.htm","desc":"Sauveniere (5 vues)"},
{"href":"sclaigneaux.htm","desc":"Sclaigneaux (12 vues)"},
{"href":"scry.htm","desc":"Scry (13 vues)"}, 
{"href":"senenne.htm","desc":"Senenne (4 vues)"},
{"href":"senzeille.htm","desc":"Senzeille (4 vues)"},
{"href":"silenrieux.htm","desc":"Silenrieux"},
{"href":"sombreffe.htm","desc":"Sombreffe (15 vues)"},
{"href":"sovet.htm","desc":"Sovet (4 vues)"},
{"href":"spontin.htm","desc":"Spontin (10 vues)"},
{"href":"spontin_sources.htm","desc":"Spontin Sources (3 vues)"},
{"href":"stave.htm","desc":"Stave (6 vues/1 plan)"}, 
{"href":"tailfer.htm","desc":"Tailfer (3 vues)"},
{"href":"tamines.htm","desc":"Tamines (23 vues)"},
{"href":"thy_le_chateau.htm","desc":"Thy-le-Château (11 vues)"},
{"href":"treignes.htm","desc":"Treignes (5 vues)"},
{"href":"vedrin.htm","desc":"Vedrin (3 vues)"},
{"href":"vierves.htm","desc":"Vierves (2 vues)"},
{"href":"vignee.htm","desc":"Vignee (2 vues)"},
{"href":"villers_le_gambon.htm","desc":"Villers le Gambon (18 vues)"}, 
{"href":"villers_sur_lesse.htm","desc":"Villers Sur Lesse (5 vues)"},
{"href":"voneche.htm","desc":"Vonêche (11 vues)"},
{"href":"walcourt.htm","desc":"Walcourt (18 vues)"},
{"href":"walzin.htm","desc":"Walzin (2 vues)"},
{"href":"wanlin.htm","desc":"Wanlin (9 vues)"},
{"href":"warnant.htm","desc":"Warnant (17 vues)"},
{"href":"warnant_vicinal.htm","desc":"Warnant vicinal"},
{"href":"waulsort.htm","desc":"Waulsort I-II (5 vues)"},
{"href":"waulsort_village.htm","desc":"Waulsort Village (III) (4 vues)"},
{"href":"wiesme.htm","desc":"Wiesme (7 vues)"},
{"href":"yves_gomezee.htm","desc":"Yves Gomezée I-II (8 vues)"},
{"href":"yvoir.htm","desc":"Yvoir I-II (1 plan + 20 vues)"},
{"href":"yvoir_carrieres.htm","desc":"Yvoir Carrières (6 vues)"},
{"href":"archennes.htm","desc":"Archennes (7 vues)","province":"=================================="},
{"href":"archennes_vicinal.htm","desc":"Archennes vicinal (3 vues)"}, 
{"href":"autre_eglise.htm","desc":"Autre Eglise (9 vues)"},
{"href":"basse_wavre.htm","desc":"Basse Wavre (6 vues)"},
{"href":"baulers.htm","desc":"Baulers (10 vues)"},
{"href":"beauvechain.htm","desc":"Beauvechain vicinale (8 vues)"},
{"href":"bierghes.htm","desc":"Bierghes (6 vues)"}, 
{"href":"blanmont.htm","desc":"Blanmont (10 vues)"},
{"href":"bousval.htm","desc":"Bousval (2 vues)"},
{"href":"braine_l_alleud.htm","desc":"Braine l'alleud (16 vues)"},
{"href":"braine_le_chateau.htm","desc":"Braine le Chateau (5 vues)"},
{"href":"ceroux.htm","desc":"Ceroux Mousty (8 vues)"},
{"href":"chapelle_saint_lambert.htm","desc":"Chapelle St Lambert Vic (3 vues)"},
{"href":"chastre.htm","desc":"Chastre I-II (8 vues)"},
{"href":"clabecq.htm","desc":"Clabecq (5 vues)"},
{"href":"court_saint_etienne.htm","desc":"Court Saint Etienne (8 vues)"},
{"href":"dongelberg.htm","desc":"Dongelberg (vicinale) (2 vues)"},
{"href":"faux.htm","desc":"Faux I-II (9 vues)"},
{"href":"florival.htm","desc":"Florival (8 vues)"},
{"href":"gastuche.htm","desc":"Gastuche (8 vues)"},
{"href":"genappe.htm","desc":"Genappe (5 vues)"},
{"href":"genval.htm","desc":"Genval II-III (17 vues)"},
{"href":"grand_leez.htm","desc":"Grand Leez Thorembais (11 vues)"},
{"href":"grez_doiceau_vicinal.htm","desc":"Grez Doiceau vicinale (7 vues)"},
{"href":"hamme_mille_vicinal.htm","desc":"Hamme Mille vicinale"},
{"href":"hedenge.htm","desc":"Hédenge (7 vues)"},
{"href":"huppaye.htm","desc":"Huppaye (9 vues)"},
{"href":"jauche.htm","desc":"Jauche (7 vues)"},
{"href":"jodoigne.htm","desc":"Jodoigne (3 vues)"},
{"href":"la_hulpe.htm","desc":"La Hulpe I-II (21 vues)"},
{"href":"la_roche.htm","desc":"La Roche (13 vues)"},
{"href":"lasnes.htm","desc":"Lasnes gare vicinale (7 vues) "},
{"href":"lillois.htm","desc":"Lillois I-II (14 vues)"},
{"href":"limal.htm","desc":"Limal (5 vues)"},  
{"href":"limelette_buston.htm","desc":"Limelette-Buston (3 vues)"},
{"href":"maransart.htm","desc":"Maransart-Aywiers gare vic (14)"},
{"href":"marbisoux.htm","desc":"Marbisoux"},
{"href":"maret.htm","desc":"Maret (6 vues)"},
{"href":"mont_saint_guibert.htm","desc":"Mont-Saint-Guibert I-II (15 vues)"}, 
{"href":"nethen.htm","desc":"Nethen vicinal (4)"},
{"href":"niderand.htm","desc":"Nidérand"},
{"href":"nivelles_est.htm","desc":"Nivelles Est (13 vues)"},
{"href":"nivelles_nord.htm","desc":"Nivelles Nord (4 vues)"},
{"href":"nodebais.htm","desc":"Nodebais (5 vues)"},
{"href":"noirhat.htm","desc":"Noirhat (3 vues)"},
{"href":"noucelles.htm","desc":"Noucelles (7 vues)"},
{"href":"oisquercq.htm","desc":"Oisquercq"},
{"href":"opheylissem.htm","desc":"Opheylissem"},
{"href":"orp.htm","desc":"Orp (10 vues)"},
{"href":"ottignies.htm","desc":"Ottignies I-II (24 vues)"},
{"href":"pecrot.htm","desc":"Pecrot (3 vues)"},
{"href":"perwez.htm","desc":"Perwez (2 vues)"},
{"href":"petit_rosiere.htm","desc":"Petit Rosière (8 vues)"},
{"href":"profondsart.htm","desc":"Profondsart I-II (9 vues)"},
{"href":"quenast.htm","desc":"Quenast (15 vues)"},
{"href":"ramillies.htm","desc":"Ramillies (22 vues)"},
{"href":"rebecq.htm","desc":"Rebecq (22 vues)"},
{"href":"rebecq_2021.htm","desc":"Rebecq-RRR en 2021 (16 vues)"}, 
{"href":"rixensart.htm","desc":"Rixensart I-II (19 vues)"},
{"href":"rognon.htm","desc":"Rognon (15 vues/2 plans)"},
{"href":"saintes.htm","desc":"Saintes (2 vues)"},
{"href":"saint_jean_geest.htm","desc":"Saint-Jean-Geest (2 vues)"},
{"href":"sart_moulin.htm","desc":"Sart Moulin (5 vues)"},
{"href":"sart_risbart.htm","desc":"Sart Risbart vicinale (17 vues)"},
{"href":"thy.htm","desc":"Thy (4 vues)"},
{"href":"tilly.htm","desc":"Tilly (6 vues)"},
{"href":"tourinnes.htm","desc":"Tourinnes-la-Grosse (3 vues)"},
{"href":"tubize.htm","desc":"Tubize I-II (11 vues)"},
{"href":"villers_la_ville.htm","desc":"Villers La Ville (6 vues)"},
{"href":"virginal.htm","desc":"Virginal (2 vues)"},
{"href":"waterloo.htm","desc":"Waterloo I-II (33 vues)"},
{"href":"wauthier.htm","desc":"Wauthier (5 vues)"},
{"href":"wavre.htm","desc":"Wavre (20 vues)"},
{"href":"zetrud.htm","desc":"Zétrud Lumay (10 vues)"},
{"href":"arlon.htm","desc":"Arlon (22 vues)","province":"=================================="},
{"href":"athus.htm","desc":"Athus (5 vues)"},
{"href":"aubange.htm","desc":"Aubange (5 vues)"},
{"href":"aye.htm","desc":"Aye (11 vues)"},
{"href":"bande.htm","desc":"Bande vicinal"},
{"href":"baranzy.htm","desc":"Baranzy (4 vues)"},
{"href":"barvaux.htm","desc":"Barvaux (10 vues)"},
{"href":"bastogne_sud.htm","desc":"Bastogne Sud (12 vues)"},
{"href":"bastogne_nord.htm","desc":"Bastogne Nord (3 vues)"},
{"href":"beho.htm","desc":"Beho"},
{"href":"belmont.htm","desc":"Belmont (4 vues)"},
{"href":"benonchamps.htm","desc":"Benonchamps (3 vues)"},
{"href":"bernimont.htm","desc":"Bernimont (3 vues)"},
{"href":"bertrix.htm","desc":"Bertrix (14 vues)"},
{"href":"bodange.htm","desc":"Bodange"},
{"href":"bomal.htm","desc":"Bomal I-II (5 vues)"},
{"href":"bouillon.htm","desc":"Bouillon (vicinale, 4 vues)"},
{"href":"bourcy.htm","desc":"Bourcy (+ vicinal) (11 + 1 vues)"},
{"href":"bovigny.htm","desc":"Bovigny (4 vues)"},
{"href":"burtonville.htm","desc":"Burtonville (+ viaduc)"}, 
{"href":"buzenol.htm","desc":"Buzenol (4 vues)"},
{"href":"carlsbourg.htm","desc":"Carlsbourg (9 vues)"},
{"href":"chatillon_vicinal.htm","desc":"Châtillon"}, 
{"href":"cierreux.htm","desc":"Cierreux"},
{"href":"corbion.htm","desc":"Corbion (vicinale)"}, 
{"href":"croix_rouge.htm","desc":"Croix Rouge (3 vues)"},
{"href":"cugnon.htm","desc":"Cugnon Mortehan"},
{"href":"etalle_vicinal.htm","desc":"Etalle vicinal"},
{"href":"ethe.htm","desc":"Ethe"},
{"href":"ethe_vicinal.htm","desc":"Ethe vicinale (2 vues)"},
{"href":"florenville.htm","desc":"Florenville (16 vues)"},
{"href":"florenville_vicinale.htm","desc":"Florenville vicinale (5)"},
{"href":"forrieres.htm","desc":"Forrières (10 vues)"},
{"href":"fouche.htm","desc":"Fouche (5 vues)"},
{"href":"gantaufet.htm","desc":"Gantaufet"},
{"href":"gouvy.htm","desc":"Gouvy (5 vues)"},
{"href":"gorcy.htm","desc":"Gorcy (FR) (3 vues)"},
{"href":"grandhalleux.htm","desc":"Grand halleux I-II (5 vues)"},
{"href":"grupont.htm","desc":"Grupont (9 vues)"},
{"href":"habay.htm","desc":"Habay la vieille (7 vues)"},
{"href":"halanzy.htm","desc":"Halanzy 23 vues)"},
{"href":"hamipre.htm","desc":"Hamipré (2 vues)"},
{"href":"hatrival.htm","desc":"Hatrival (17 vues)"},
{"href":"herbeumont.htm","desc":"Herbeumont (3 vues)"},
{"href":"houdemont.htm","desc":"Houdemont (3 vues)"},
{"href":"houdrigny.htm","desc":"Houdrigny"},
{"href":"houffalize.htm","desc":"Houffalize vicinale (10)"},
{"href":"izel.htm","desc":"Izel (6 vues)"},
{"href":"jamoigne.htm","desc":"Jamoigne (3 vues)"},
{"href":"lacuisine.htm","desc":"Lacuisine (7 vues)"},
{"href":"lamorteau.htm","desc":"Lamorteau (6 vues)"},
{"href":"laroche_vicinal.htm","desc":"Laroche vicinal (15 vues)"},
{"href":"lavacherie.htm","desc":"Lavacherie"},
{"href":"lavaux.htm","desc":"Lavaux (3 vues)"}, 
{"href":"les_epioux.htm","desc":"Les Epioux (8 vues)"},
{"href":"lesterny.htm","desc":"Lesterny"},
{"href":"libin.htm","desc":"Libin vicinal"},
{"href":"libramont.htm","desc":"Libramont (6 vues)"},
{"href":"limerle.htm","desc":"Limerlé (4 vues)"},
{"href":"longlier.htm","desc":"Longlier Neufchâteau (30 vues)"},
{"href":"maissin.htm","desc":"Maissin vicinal"}, 
{"href":"manhay.htm","desc":"Manhay vicinal (5 vues)"},
{"href":"marbehan.htm","desc":"Marbehan I-II (5 vues)"},
{"href":"marche.htm","desc":"Marche-en-Famenne (14 vues)"},
{"href":"marloie_vicinal.htm","desc":"Marloie vicinal (6 vues)"}, 
{"href":"marloie.htm","desc":"Marloie I-II (19 vues)"},
{"href":"martelange.htm","desc":"Martelange vicinal (3 vues)"},
{"href":"meix_devant_virton.htm","desc":"Meix devant Virton (9 vues)"}, 
{"href":"mellier.htm","desc":"Mellier (10 vues)"},
{"href":"messancy.htm","desc":"Messancy (4 vues)"},
{"href":"melreux.htm","desc":"Melreux Hotton (4 vues)"},
{"href":"mirwart.htm","desc":"Mirwart (2 vues)"}, 
{"href":"morhet.htm","desc":"Morhet (2 vues)"}, 
{"href":"muno.htm","desc":"Muno (9 vues)"},
{"href":"musson.htm","desc":"Musson (12 vues)"},
{"href":"longlier.htm","desc":"Neufchâteau (30 vues) > voir Longlier"},
{"href":"neuvillers.htm","desc":"Neuvillers"},
{"href":"offagne.htm","desc":"Offagne"},
{"href":"opont.htm","desc":"Opont vicinale"},
{"href":"orgeo.htm","desc":"Orgéo"},
{"href":"ourt.htm","desc":"Ourt (5 vues)"}, 
{"href":"paliseul.htm","desc":"Paliseul (15 vues)"},
{"href":"pierrard.htm","desc":"Pierrard (Ecole)"}, 
{"href":"pin.htm","desc":"Pin (3 vues)"}, 
{"href":"poix.htm","desc":"Poix (17 vues)"},
{"href":"poix_saint_hubert_vicinal.htm","desc":"Poix-St-Hubert Vicinale (2 vues)"},
{"href":"recogne.htm","desc":"Recogne (7 vues)"},
{"href":"rencheux.htm","desc":"Rencheux (3 vues)"},
{"href":"resteigne.htm","desc":"Resteigne vicinal (2 vues)"},
{"href":"rosieres.htm","desc":"Rosières (6 vues)"},
{"href":"rossart.htm","desc":"Rossart (11 vues)"},
{"href":"ruette.htm","desc":"Ruette (3 vues)"},
{"href":"saint_hubert_vicinal.htm","desc":"Saint Hubert Vicinal (4 vues)"},
{"href":"saint_leger_vicinal.htm","desc":"Saint Léger Vicinal (4 vues)"},  
{"href":"saint_medard.htm","desc":"Saint Médard (10 vues)"},
{"href":"saint_vincent_bellefontaine.htm","desc":"Saint Vincent Bel (18)"},
{"href":"saint_vincent_bellefontaine_vicinal.htm","desc":"Saint Vincent Bel. Vic. (2)"},
{"href":"sainte_marie_sur_semois.htm","desc":"Sainte Marie [Sur Semois] (3)"},
{"href":"sibret.htm","desc":"Sibret (8 vues)"},
{"href":"signeulx.htm","desc":"Signeulx (7 vues)"},
{"href":"sterpenich.htm","desc":"Sterpenich (7 vues)"},
{"href":"stockem.htm","desc":"Stockem (20 vues)"},
{"href":"straimont.htm","desc":"Straimont"}, 
{"href":"tavigny.htm","desc":"Tavigny (9 vues)"},
{"href":"turpange.htm","desc":"Turpange (3 vues)"},
{"href":"vielsalm.htm","desc":"Vielsalm (10 vues + viaduc)"},
{"href":"villeroux.htm","desc":"Villeroux (3 vues)"},
{"href":"villers_sur_semois.htm","desc":"Vilers-sur-Semois (7 vues)"},
{"href":"virton.htm","desc":"Virton (Saint Mard) (26 vues)"},
{"href":"virton_ville.htm","desc":"Virton (Ville) (5 vues)"},
{"href":"viville.htm","desc":"Viville (6 vues)"},
{"href":"wellin_vicinal.htm","desc":"Wellin Vicinal (5 vues)."},
{"href":"wideumont.htm","desc":"Wideumont (7 vues)"},
{"href":"amay.htm","desc":"Amay (4 vues)","province":"=================================="},
{"href":"ampsin.htm","desc":"Ampsin (6 vues)"},
{"href":"angleur.htm","desc":"Angleur I-II (6 vues)"},
{"href":"ans.htm","desc":"Ans (4 vues)"},
{"href":"ans_est.htm","desc":"Ans Est (3 vues)"},
{"href":"argenteau.htm","desc":"Argenteau (11 vues)"},
{"href":"astenet.htm","desc":"Astenet (2 vues)"},
{"href":"aubel.htm","desc":"Aubel (13 vues)"},
{"href":"avennes.htm","desc":"Avennes (3 vues/1 plan)"},
{"href":"avernas.htm","desc":"Avernas (2 vues/1 plan)"},
{"href":"aywaille.htm","desc":"Aywaille (10 vues)"},
{"href":"barse.htm","desc":"Barse (7 vues)"},
{"href":"bas_oha.htm","desc":"Bas-Oha (4 vues)"},
{"href":"bassenge.htm","desc":"Bassenge"}, 
{"href":"battice.htm","desc":"Battice (6 vues)"},
{"href":"beyne.htm","desc":"Beyne (6 vues)"},
{"href":"bierset.htm","desc":"Bierset I-II [Awans] (5 vues)"},
{"href":"bleyberg.htm","desc":"Bleyberg / Plombières (11 vues)"},
{"href":"bois_de_breux.htm","desc":"Bois de Breux (2 vues)"},
{"href":"braives.htm","desc":"Braives (7 vues + 1 plan)"},
{"href":"bressoux.htm","desc":"Bressoux I-II-III (6 vues-1 plan)"},
{"href":"bullange.htm","desc":"BÃ¼llingen/Bullange (2 vues)"},
{"href":"burdinne.htm","desc":"Burdinne (22 vues)"},
{"href":"butgenbach.htm","desc":"BÃ¼tgenbach (2 vues)"},
{"href":"chaineux.htm","desc":"Chaineux (2 vues)"},
{"href":"chanxhe.htm","desc":"Chanxhe (2 vues)"},
{"href":"chaudfontaine.htm","desc":"Chaudfontaine (30 vues)"},
{"href":"chenee.htm","desc":"Chênée II (3 vues)"},
{"href":"cheneeIII.htm","desc":"Chênée III (16 vues/1 plan)"},
{"href":"cheratte.htm","desc":"Cheratte (2 vues)"},
{"href":"clavier.htm","desc":"Clavier (10 vues-1 plan)"},
{"href":"comblain_au_pont.htm","desc":"Comblain au Pont (11 vues)"},
{"href":"comblain_la_tour.htm","desc":"Comblain la Tour I-II (24 vues)"},
{"href":"coo.htm","desc":"Coo II (5 vues)"}, 
{"href":"cornesse.htm","desc":"Cornesse"},
{"href":"corswarem.htm","desc":"Corswarem (2 vues)"},
{"href":"dison.htm","desc":"Dison (5 vues)"},
{"href":"dolhain.htm","desc":"Dolhain Gileppe (4 vues)"},
{"href":"dolhain_II.htm","desc":"Dolhain Gileppe II (22 vues)"},
{"href":"dolhain_vicinal.htm","desc":"Dolhain Vicinal (4 vues)"},
{"href":"elsenborn.htm","desc":"Elsenborn (2 vues)"},
{"href":"engis.htm","desc":"Engis (8 vues)"},
{"href":"ensival.htm","desc":"Ensival I-II (4 vues)"},
{"href":"envoz.htm","desc":"Envoz (10 vues)"},
{"href":"esneux.htm","desc":"Esneux (13 vues)"},
{"href":"eupen.htm","desc":"Eupen I-II (4 vues/2 plans)"},
{"href":"eupen_vicinal.htm","desc":"Eupen vicinal"},
{"href":"fallais.htm","desc":"Fallais (+ 1 plan)"},
{"href":"faymonville.htm","desc":"Faymonville"},
{"href":"fexhe_le_haut_clocher.htm","desc":"Fexhe Le Haut C. (11 vues)"},
{"href":"flemalle_grande.htm","desc":"Flemalle Grande (5 vues)"},
{"href":"flemalle_haute.htm","desc":"Flemalle Haute (11 vues)"},
{"href":"fleron.htm","desc":"Fléron (8 vues)"},
{"href":"fleury.htm","desc":"Fleury (1 vue/1 plan)"},
{"href":"fourneau.htm","desc":"Fourneau (2 vues/1 plan)"},
{"href":"fraipont.htm","desc":"Fraipont (18 vues)"},
{"href":"franchimont.htm","desc":"Franchimont (9 vues)"},
{"href":"francorchamps.htm","desc":"Francorchamps (7 vues)"},
{"href":"froidthier.htm","desc":"Froidthier (3 vues)"},
{"href":"fumal.htm","desc":"Fumal (3 vues/1 plan)"},
{"href":"gemmenich.htm","desc":"Gemmenich (14 vues)"},
{"href":"glons.htm","desc":"Glons (17 vues)"},
{"href":"goffontaine.htm","desc":"Goffontaine (2 vues)"},
{"href":"gomze_andoumont.htm","desc":"Gomzé Andoumont vicinal"}, 
{"href":"hamoir.htm","desc":"Hamoir (15 vues)"},
{"href":"hannut.htm","desc":"Hannut (9 vues/1 plan)"}, 
{"href":"haute_flone.htm","desc":"Haute FlÃ´ne (5 vues)"}, 
{"href":"henne.htm","desc":"Henne Chèvremont(4 vues)"},
{"href":"henri_chapelle.htm","desc":"Henri Chapelle"}, 
{"href":"herbestal.htm","desc":"Herbesthal (7 vues)"},
{"href":"herbestal_2019.htm","desc":"Herbesthal en 2019 (42 vues)"},
{"href":"hergenrath.htm","desc":"Hergenrath II (14 vues)"},
{"href":"hermalle_sous_huy.htm","desc":"Hermalle S Huy (8 vues)"}, 
{"href":"herstal.htm","desc":"Herstal I-II (9 vues)"}, 
{"href":"herstal_2017.htm","desc":"Herstal 2017 (6 vues)"},
{"href":"herve.htm","desc":"Herve I-II-III (12 vues)"},
{"href":"hindel_bas.htm","desc":"Hindel bas"}, 
{"href":"hockai.htm","desc":"Hockai (16 vues)"},
{"href":"hombourg.htm","desc":"Hombourg (16 vues)"},
{"href":"hony.htm","desc":"Hony (6 vues)"},
{"href":"huccorgne.htm","desc":"Huccorgne (3 vues/1 plan)"},
{"href":"huy_ville.htm","desc":"Huy Ville (5 vues/1 plan)"}, 
{"href":"huy_nord_I.htm","desc":"Huy Nord I (21 vues)"},
{"href":"huy_nord_II.htm","desc":"Huy Nord II (3 vues)"},
{"href":"huy_saint_hilaire.htm","desc":"Huy St Hilaire (10 vues/1 plan)"}, 
{"href":"huy_sud.htm","desc":"Huy Sud 11 vues/1 plan)"},
{"href":"java.htm","desc":"Java"},
{"href":"jemeppe_sur_meuse.htm","desc":"Jemeppe Sur Meuse (5 vues)"},
{"href":"jupille.htm","desc":"Jupille"}, 
{"href":"juslenville.htm","desc":"Juslenville (11 vues)"},
{"href":"kalterherberg.htm","desc":"Kalterherberg (6 vues)"},
{"href":"kinkempois.htm","desc":"Kinkempois I-II (6 vues)"}, 
{"href":"konzen.htm","desc":"Konzen (2 vues)"}, 
{"href":"la_brouck.htm","desc":"La Brouck (2 vues)"}, 
{"href":"la_gleize.htm","desc":"La Gleize (5 vues)"},
{"href":"la_prealle.htm","desc":"La Préalle"},
{"href":"la_reid.htm","desc":"La Reid (2 vues)"},
{"href":"lambermont.htm","desc":"Lambermont (2 vues)"}, 
{"href":"lammersdorf.htm","desc":"Lammersdorf (3 vues)"},  
{"href":"lengeler.htm","desc":"Lengeler (3 vues)"}, 
{"href":"les_avins_en_condroz.htm","desc":"Les Avins en Condroz (10 vues)"},
{"href":"liege_jonfosse.htm","desc":"Liège Carré (5 vues/1 plan)"},
{"href":"liege_guillemins_I.htm","desc":"Liège Guillemins I (2 vues)"},
{"href":"liege_guillemins_II.htm","desc":"Liège Guillemins II (9 vues)"},
{"href":"liege_guillemins_III.htm","desc":"Liège Guillemins III (7 vues)"},
{"href":"liege_guillemins_IV.htm","desc":"Liège Guillemins IV (9 vues)"},
{"href":"liege_haut_pre.htm","desc":"Liège Haut pré (3 vues/1 plan)"},
{"href":"liege_jonfosse.htm","desc":"Liège Jonfosse (5 vues/1 plan)"},
{"href":"liege_longdoz.htm","desc":"Liège Longdoz (15 vues/3 plans)"},
{"href":"liege_longdoz_1982.htm","desc":"Liège Longdoz 1982(2 vues/bonus)"}, 
{"href":"liege_longdoz_fin.htm","desc":"Liège Longdoz démolition (12 planches)"}, 
{"href":"liege_montegnee.htm","desc":"Liège Montegnée"},
{"href":"liege_palais.htm","desc":"Liège Palais I-II-III (16 vues/1 plan)"},
{"href":"liege_palais.htm","desc":"Liège Saint Lambert"},
{"href":"liege_vivegnis.htm","desc":"Liège Vivegnis (4 vues/1 c)"},
{"href":"lierneux.htm","desc":"Lierneux gare vicinale (8 vues)"}, 
{"href":"liers.htm","desc":"Liers (9 vues)"},
{"href":"lincent.htm","desc":"Lincent (3 vues)"}, 
{"href":"liotte.htm","desc":"Liotte (5 vues)"},
{"href":"lommersweiler.htm","desc":"Lommersweiler (2 vues)"},
{"href":"lorce_chevron.htm","desc":"Nazé > Lorcé-Chevron (3)"},
{"href":"losheimergraben.htm","desc":"Losheimergraben (3 vues)"}, 
{"href":"malmedy.htm","desc":"Malmedy I-II (10 vues)"},
{"href":"marchin.htm","desc":"Marchin (2 vues)"}, 
{"href":"marteau.htm","desc":"Marteau"},
{"href":"martinrive.htm","desc":"Martinrive (2 vues)"},
{"href":"masta.htm","desc":"Masta"}, 
{"href":"meiz.htm","desc":"Meiz"},  
{"href":"melen.htm","desc":"Melen(3 vues)"},
{"href":"mery.htm","desc":"Méry I-II (11 vues)"},
{"href":"micheroux.htm","desc":"Micheroux (8 vues)"},
{"href":"milmort.htm","desc":"Milmort (6 vues)"},
{"href":"modave.htm","desc":"Modave (4 vues/1 plan)"},
{"href":"modave_village.htm","desc":"Modave village (5 vues/1 plan)"}, 
{"href":"moha.htm","desc":"Moha (3 vues/1 plan)"},
{"href":"momalle.htm","desc":"Momalle (8 vues)"}, 
{"href":"monschau.htm","desc":"Monschau/Montjoie I-II (5 vues)"}, 
{"href":"montenau.htm","desc":"Montenau (3 vues)"},
{"href":"montzen.htm","desc":"Montzen (2 vues)"},
{"href":"moresnet.htm","desc":"Moresnet (7 vues)"},
{"href":"nessonvaux.htm","desc":"Nessonvaux (25 vues)"},
{"href":"niveze.htm","desc":"Nivezé"},
{"href":"nonceveux.htm","desc":"Nonceveux"},
{"href":"ougree.htm","desc":"Ougrée I-II (8 vues)"}, 
{"href":"pepinster_I.htm","desc":"Pepinster I (0 vue)"},
{"href":"pepinster_II.htm","desc":"Pepinster II (8 vues)"},
{"href":"pepinster_III.htm","desc":"Pepinster III (15 vues)"},
{"href":"pepinster_cite.htm","desc":"Pepinster Cité (8 vues)"},
{"href":"plombieres.htm","desc":"Plombières (Bleyberg) (6 vues)"},
{"href":"pont_d_argenteau.htm","desc":"Pont d' Argenteau (3 vues)"},     
{"href":"poulseur.htm","desc":"Poulseur II (16 vues)"},
{"href":"quarreux.htm","desc":"Quarreux"},
{"href":"racour.htm","desc":"Racour (13 vues)"},
{"href":"raeren.htm","desc":"Raeren (9 vues)"}, 
{"href":"recht.htm","desc":"Recht (4 vues)"}, 
{"href":"regissa.htm","desc":"Regissa (2 vues)"},
{"href":"remicourt.htm","desc":"Remicourt (8 vues)"},
{"href":"remouchamps.htm","desc":"Remouchamps (12 vues)"},
{"href":"retinne.htm","desc":"Retinne (5 vues)"},
{"href":"reuland.htm","desc":"Reuland (9 vues)"},
{"href":"rivage.htm","desc":"Rivage (24 vues)"},
{"href":"roanne.htm","desc":"Roanne Coo (5 vues)"},
{"href":"rocourt.htm","desc":"Rocourt (6 vues)"},
{"href":"roetgen.htm","desc":"Roetgen (3 vues)"},
{"href":"roiseux.htm","desc":"Roiseux (2 vues/1plan)"}, 
{"href":"saint_severin.htm","desc":"Saint Séverin (5 vues)"},
{"href":"saint_vith.htm","desc":"Saint Vith (8 vues)"},
{"href":"sainval.htm","desc":"Sainval (7 vues)"}, 
{"href":"sart_lez_spa.htm","desc":"Sart Lez Spa (9 vues)"},
{"href":"sauheid.htm","desc":"Sauheid"},
{"href":"sclessin.htm","desc":"Sclessin (3 vues)"},
{"href":"seraing.htm","desc":"Seraing I-II (5 vues)"},
{"href":"sourbrodt.htm","desc":"Sourbrodt (13 vues)"},
{"href":"sourbrodt_2022.htm","desc":"Sourbrodt en 2022 (21 vues)"},
{"href":"souverain_wandre.htm","desc":"Souverain-Wandre"},
{"href":"souverain_pre.htm","desc":"Souverain-Pré"}, 
{"href":"souvre.htm","desc":"Souvré (3 vues)"}, 
{"href":"spa_I.htm","desc":"Spa I (2 vues)"}, 
{"href":"spa.htm","desc":"Spa II (13 vues)"},
{"href":"spa_geronstere.htm","desc":"Spa-Géronstère (14 vues)"},
{"href":"statte.htm","desc":"Statte (17 vues)"},
{"href":"statte_vicinale.htm","desc":"Statte gare vicinale (2 vues)"},
{"href":"stavelot.htm","desc":"Stavelot"},               
{"href":"steinebruck.htm","desc":"Steinebruck (2 vues)"},
{"href":"stoumont.htm","desc":"Stoumont (5 vues)"},
{"href":"sy.htm","desc":"Sy (12 vues)"},
{"href":"theux.htm","desc":"Theux (17 vues)"},
{"href":"thimister.htm","desc":"Thimister-Clermont (2 vues)"},
{"href":"tilff.htm","desc":"Tilff (21 vues)"},
{"href":"tilleur.htm","desc":"Tilleur (2 vues)"},
{"href":"trooz.htm","desc":"Trooz (6 vues)"},
{"href":"trois_ponts.htm","desc":"Trois Ponts II (11 vues)"},
{"href":"val_saint_lambert.htm","desc":"Val Saint Lambert (7 vues/1 plan/2 bonus)"},
{"href":"val_saint_lambert_vicinal.htm","desc":"Val Saint Lambert Vicinal"},
{"href":"vaux_sous_chevremont.htm","desc":"Vaux S Ch (2 vues)"},
{"href":"verlaine_vicinal.htm","desc":"Verlaine gare vicinale"},
{"href":"verviers_ouest.htm","desc":"Verviers Ouest (7 vues)"},
{"href":"verviers_est.htm","desc":"Verviers Est (4 vues)"},
{"href":"verviers.htm","desc":"Verviers Central (8 vues)"},
{"href":"verviers_galerie_2016.htm","desc":"Verviers C 2015-2016 (15 photos)"},
{"href":"verviers_galerie_2019.htm","desc":"Verviers C 2019 (21 photos)"},
{"href":"verviers_matadi.htm","desc":"Verviers Matadi (5 vues)"}, 
{"href":"verviers_palais.htm","desc":"Verviers Palais (2 vues)"},
{"href":"vinalmont.htm","desc":"Vinalmont"}, 
{"href":"vise_I.htm","desc":"Visé I (3 vues/1 plan)"}, 
{"href":"vise_II.htm","desc":"Visé II (3 vues/1 plan)"}, 
{"href":"vise_III.htm","desc":"Visé III (2 vues/1 plan)"},
{"href":"vise_IV.htm","desc":"Visé IV (14 vues/1 plan)"}, 
{"href":"vyle_tharoul.htm","desc":"Vyle (et) Tharoul (4 vues/1 plan)"}, 
{"href":"waimes.htm","desc":"Waimes (8 vues)"},
{"href":"wandre.htm","desc":"Wandre"},
{"href":"waremme.htm","desc":"Waremme I-II (26 vues)"},
{"href":"waremme_vicinal.htm","desc":"Waremme gare vicinale (2 vues)"},
{"href":"warsage.htm","desc":"Warsage (2 vues)"},
{"href":"welkenraedt.htm","desc":"Welkenraedt I-II-III (23 vues)"},
{"href":"welkenraedt_ouest.htm","desc":"Welkenraedt Ouest"},
{"href":"weywertz.htm","desc":"Weywertz I-II-III (8 vues)"},
{"href":"acoz.htm","desc":"Acoz (18 vues)","province":"=================================="},
{"href":"acren.htm","desc":"Acren (11 vues)"},
{"href":"aiseau.htm","desc":"Aiseau (7 vues)"},
{"href":"amougies.htm","desc":"Amougies"},
{"href":"anderlues.htm","desc":"Anderlues (14 vues)"},
{"href":"angre.htm","desc":"Angre (4 vues)"},
{"href":"angreau.htm","desc":"Angreau"},
{"href":"antoing.htm","desc":"Antoing I-II-III (11 vues)"},
{"href":"anvaing.htm","desc":"Anvaing"},
{"href":"ath.htm","desc":"Ath (13 vues + 1 plan)"},
{"href":"audregnies.htm","desc":"Audregnies (2 vues)"},
{"href":"barry_maulde.htm","desc":"Barry Maulde (2 vues)"},
{"href":"bascoup.htm","desc":"Bascoup (6 vues)"},
{"href":"bascoup_etat.htm","desc":"Bascoup Etat (+ 1 plan)"},
{"href":"basecles.htm","desc":"Basècles (3 vues)"},
{"href":"basecles_carrieres.htm","desc":"Basècles Carrières (2 vues)"},
{"href":"bassilly.htm","desc":"Bassilly (11 vues / 1 plan)"}, 
{"href":"baudour.htm","desc":"Baudour (4 vues)"},
{"href":"beaumont.htm","desc":"Beaumont (4 vues)"},
{"href":"beignee.htm","desc":"Beignée I-II (11 vues)"},
{"href":"bellecourt.htm","desc":"Bellecourt"},
{"href":"beloeil.htm","desc":"Beloeil (4 vues)"},
{"href":"bernissart.htm","desc":"Bernissart (10 vues)"},
{"href":"bienne_lez_happart.htm","desc":"Bienne lez Happart (3 vues)"},
{"href":"binche_I.htm","desc":"Binche I (5 vues)"},
{"href":"binche_II.htm","desc":"Binche II (18 vues)"},
{"href":"binche_2017.htm","desc":"Binche II en 2017 (14 vues)"},
{"href":"binche_2019.htm","desc":"Binche II en 2019 (40 vues)"},
{"href":"blandain.htm","desc":"Blandain (12 vues)"},
{"href":"blaregnies.htm","desc":"Blaregnies (2 vues)"}, 
{"href":"blaton.htm","desc":"Blaton I-II (7 vues)"},
{"href":"bleharie.htm","desc":"Bléharies (2 vues)"},
{"href":"bois_du_luc.htm","desc":"Bois du Luc"},
{"href":"bois_noel.htm","desc":"Bois NoÃ«l"},
{"href":"bomeree.htm","desc":"Bomerée"},
{"href":"bonne_esperance.htm","desc":"Bonne Espérance I-II (9 vues)"},
{"href":"bouffioulx.htm","desc":"Bouffioulx (2 vues)"},
{"href":"boussu.htm","desc":"Boussu I-II (22 vues)"},
{"href":"boussu_bois.htm","desc":"Boussu-Bois (1 vue-1 plan)"},
{"href":"boussu_haine.htm","desc":"Boussu-Haine (2 vues)"},
{"href":"boussu_route.htm","desc":"Boussu-Route (2 vues-1 plan)"},
{"href":"bracquegnies.htm","desc":"Bracquegnies I-II (12 vues)"}, 
{"href":"braine_le_comte.htm","desc":"Braine Le Comte (13 vues)"},
{"href":"braine_le_comte_2015_2019.htm","desc":"Braine Le Comte 2015-2016 (16 PH)"},
{"href":"brugelette.htm","desc":"Brugelette I-II (12 vues)"},
{"href":"buvrinnes.htm","desc":"Buvrinnes(3 vues)"},
{"href":"callenelle.htm","desc":"Callenelle (4 vues)"},
{"href":"cambron.htm","desc":"Cambron Casteau (6 vues)"},
{"href":"carnieres.htm","desc":"Carnières (15 vues)"},
{"href":"celles_escanaffles.htm","desc":"Celles Escanaffles"},
{"href":"chapelle_a_wattines.htm","desc":"Chapelle Ã  Wattines"},
{"href":"charleroi_ouest.htm","desc":"Charleroi Ouest I-II-III (23 vues)"},
{"href":"charleroi_sud.htm","desc":"Charleroi Sud (22 vues)"},
{"href":"charleroi_sud_vicinal.htm","desc":"Charleroi Sud TEC (10 vues)"}, 
{"href":"charleroi_ville_haute.htm","desc":"Charleroi Ville Haute (3 vues)"},
{"href":"chassart.htm","desc":"Chassart (1 vue + 1 plan)"}, 
{"href":"chatelineau_chatelet.htm","desc":"Chatelineau Châtelet II III (9 vues)"},
{"href":"chercq.htm","desc":"Chercq"},
{"href":"chievres.htm","desc":"Chievres (5 vues)"},
{"href":"chimay.htm","desc":"Chimay (23 vues)"},
{"href":"comines.htm","desc":"Comines I-II (7 vues)"},
{"href":"commune.htm","desc":"Commune (5 vues + 1 plan)"},
{"href":"couillet_centre.htm","desc":"Couillet Centre (20 vues)"},
{"href":"couillet_montignies.htm","desc":"Couillet Montignies (7 vues)"},
{"href":"courcelles_centre.htm","desc":"Courcelles Centre (14 vues)"},
{"href":"courcelles_motte.htm","desc":"Courcelles Motte I-II (11 vues)"},
{"href":"cour_sur_heure.htm","desc":"Cour Sur Heure (12 vues)"},
{"href":"cronfestu.htm","desc":"Cronfestu (2 vues)"},
{"href":"cuesmes_etat.htm","desc":"Cuesmes Etat (13 vues)"},
{"href":"cuesmes_nord.htm","desc":"Cuesmes Nord (4 vues)"},
{"href":"dampremy.htm","desc":"Dampremy Charbonnage (5 vues)"},
{"href":"la_planche.htm","desc":"[Dampremy] La Planche"},
{"href":"dergneau.htm","desc":"Dergneau (8 vues)"},
{"href":"acren.htm","desc":"Deux Acren (voir Acren)"},
{"href":"dottignies.htm","desc":"Dottignies Saint Léger I-II (8 vues)"},
{"href":"dour.htm","desc":"Dour (4 vues/2 plans)"},
{"href":"ecaussinnes_carrieres.htm","desc":"Ecaussinnes (Carrières) I (18 vues)"},
{"href":"ecaussinnes_nord.htm","desc":"Ecaussinnes Nord (6 vues)"},
{"href":"ellezelles.htm","desc":"Ellezelles (3 vues)"},
{"href":"elouges.htm","desc":"Elouges (3 vues)"},
{"href":"enghien.htm","desc":"Enghien (17 vues)"},
{"href":"erbisoeul.htm","desc":"Erbisoeul [BrÃ»lotte] (5 vues)"},  
{"href":"erbisoeul_herchies.htm","desc":"Erbisoeul-Herchies"}, 
{"href":"erquelinnes.htm","desc":"Erquelinnes (21 vues)"},
{"href":"erquelinnes_village.htm","desc":"Erquelinnes village (5 vues)"},
{"href":"estinnes.htm","desc":"Estinnes (11 vues)"},
{"href":"familleureux.htm","desc":"Familleureux (5 vues)"},
{"href":"farciennes.htm","desc":"Farciennes (14 vues)"},
{"href":"fauquez.htm","desc":"Fauquez (3 vues)"},
{"href":"fauroeulx.htm","desc":"Fauroeulx (10 vues)"},
{"href":"feluy_arquennes.htm","desc":"Feluy Arquennes I-II (10 vues)"},
{"href":"flenu_produits.htm","desc":"Flénu Produits (6 vues/2 plans)"},
{"href":"fleurus.htm","desc":"Fleurus (11 vues)"},
{"href":"flobecq.htm","desc":"Flobecq (3 vues)"},
{"href":"flobecqbois.htm","desc":"Flobecq bois (3 vues)"},
{"href":"flobecq_tram.htm","desc":"Flobecq vicinal"},
{"href":"fontaine_valmont.htm","desc":"Fontaine Valmont (6 vues)"},
{"href":"fontaine_l_eveque.htm","desc":"Fontaine L'Evêque (2 vues) "},
{"href":"forchies.htm","desc":"Forchies(-la-Marche) I (11 vues)"},
{"href":"forchiesII.htm","desc":"Forchies II (4 vues)"}, 
{"href":"forges_lez_chimay.htm","desc":"Forges lez Chimay vic (15)"},
{"href":"frameries.htm","desc":"Frameries I-II (13 vues/2 plans)"},
{"href":"frasnes_lez_buissenal.htm","desc":"Frasnes-lez-Anvaing (16 vues)"},  
{"href":"frasnes_lez_buissenal.htm","desc":"Frasnes-lez-Buissenal (16 vues)"},
{"href":"frasnes_lez_gosselies.htm","desc":"Frasnes lez Gosselies (5 vues)"},
{"href":"froidchapelle.htm","desc":"Froidchapelle (8 vues)"},
{"href":"froidmont.htm","desc":"Froidmont"},
{"href":"froyennes.htm","desc":"Froyennes (14 vues)"}, 
{"href":"genly.htm","desc":"Genly (8 vues)"},
{"href":"gerpinnes.htm","desc":"Gerpinnes (7 vues)"},
{"href":"ghislenghien.htm","desc":"Ghislenghien (14 vues)"},
{"href":"ghlin.htm","desc":"Ghlin (9 vues)"}, 
{"href":"ghoy.htm","desc":"Ghoy (2 vues)"},
{"href":"gilly_sart_allet.htm","desc":"Gilly Sart Allet (27 vues)"},
{"href":"gilly_sart_culpart.htm","desc":"Gilly Sart culpart (5 vues)"},
{"href":"godarville.htm","desc":"Godarville (20 vues)"},
{"href":"gosselies.htm","desc":"Gosselies (12 vues)"},
{"href":"gosselies_vicinal.htm","desc":"Gosselies Vicinale (3 vues)"},
{"href":"gosselies_le_carosse.htm","desc":"Gosselies Le Carosse (2) "},
{"href":"gougnies.htm","desc":"Gougnies (6 vues)"},
{"href":"gouy_lez_pieton.htm","desc":"Gouy lez Piéton (9 vues)"},
{"href":"grandglise.htm","desc":"Grandglise"},
{"href":"grandmetz.htm","desc":"Grandmetz (6 vues)"},
{"href":"grand_reng_.htm","desc":"Grand Reng (5 vues)"},
{"href":"haine_saint_paul.htm","desc":"Haine St Pierre form (2 vues/2 plans)"},
{"href":"haine_saint_pierre_I.htm","desc":"Haine-St-Pierre I (22 vues/2 plans)"},
{"href":"haine_saint_pierre_2016_2019.htm","desc":"Haine-St-Pierre 2016/2019 (17 v)"},
{"href":"haine_saint_pierre_II.htm","desc":"Haine-St-Pierre II (5 vues/2 plans)"}, 
{"href":"hainin.htm","desc":"Hainin I-II (9 vues)"},
{"href":"ham_sur_heure.htm","desc":"Ham Sur Heure (16 vues)"},
{"href":"hamendes.htm","desc":"Hamendes"},
{"href":"harchies.htm","desc":"Harchies (10 vues)"},
{"href":"harmignies.htm","desc":"Harmignies (2 vues)"},
{"href":"hautrage_etat.htm","desc":"Hautrage Etat (2 vues)"},
{"href":"havinnes.htm","desc":"Havinnes (2 vues)"},
{"href":"havre.htm","desc":"Havre I-II (5 vues)"},
{"href":"hayettes.htm","desc":"Hayettes (3 vues - 2 plans)"},
{"href":"hellebecq.htm","desc":"Hellebecq (7 vues - 1 plan)"},
{"href":"hennuyeres.htm","desc":"Hennuyères (15 vues)"},
{"href":"henripont.htm","desc":"Henripont (3 vues)"},
{"href":"herinnes_warcoing.htm","desc":"Hérinnes Warcoing (2 vues)"},
{"href":"herseaux.htm","desc":"Herseaux (11 vues)"},
{"href":"herseaux_place.htm","desc":"Herseaux Place"},
{"href":"hollain.htm","desc":"Hollain (4 vues)"}, 
{"href":"hornu.htm","desc":"Hornu"},
{"href":"houdeng_goegnies.htm","desc":"Houdeng Goegnies (9 vues)"},
{"href":"houraing.htm","desc":"Houraing (9 vues / 1 plan)"},  
{"href":"hourpes.htm","desc":"Hourpes (31 vues)"},
{"href":"huissignies.htm","desc":"Huissignies (3 vues)"},
{"href":"hyon.htm","desc":"Hyon Ciply (4 vues/1 plan)"},
{"href":"isieres.htm","desc":"Isières (6 vues/1 plan)"},
{"href":"jamioulx.htm","desc":"Jamioulx (12 vues)"},
{"href":"jemappes.htm","desc":"Jemappes (19 vues)"},
{"href":"jumet.htm","desc":"Jumet Brulotte (13 vues)"},
{"href":"jumet_hamendes.htm","desc":"Jumet Hamendes (11 vues)"},
{"href":"jurbise.htm","desc":"Jurbise II (6 vues)"},
{"href":"kain.htm","desc":"Kain (5 vues)"}, 
{"href":"la_buissiere.htm","desc":"La Buissière (5 vues)"},
{"href":"la_croyere.htm","desc":"La Croyère (17 vues/1 plan)"},
{"href":"la_louviere_bouvy.htm","desc":"La Louvière Bouvy (6 vues/2 plans)"}, 
{"href":"la_louviere_centre.htm","desc":"La Louvière Centre II-III (11/2)"},
{"href":"la_louviere_centre_2019.htm","desc":"La Louvière Centre III 2019 (28)"}, 
{"href":"la_louviere_sud.htm","desc":"La Louvière Sud I-II (22 vues/2 plans)"},
{"href":"ladeuze.htm","desc":"Ladeuze"},
{"href":"lambusart.htm","desc":"Lambusart (2 vues)"},
{"href":"landelies.htm","desc":"Landelies (10 vues)"},
{"href":"lanquesaint.htm","desc":"Lanquesaint (5 vues)"},
{"href":"la_planche.htm","desc":"[Dampremy] La Planche"}, 
{"href":"le_campinaire.htm","desc":"Le Campinaire (9 vues)"},
{"href":"leers.htm","desc":"Leers Nord (2 vues)"},
{"href":"lens.htm","desc":"Lens (4 vues)"},
{"href":"le_roeulx.htm","desc":"Le RÅ“ulx"},
{"href":"lessines.htm","desc":"Lessines (5 vues)"},
{"href":"lessines_carrieres.htm","desc":"Lessines Carrières (4 vues)"},
{"href":"leuze.htm","desc":"Leuze (17 vues)"},
{"href":"leval.htm","desc":"Leval (19 vues)"},
{"href":"le_vieux_campinaire.htm","desc":"Le Vieux Campinaire (2 vues)"},
{"href":"ligne.htm","desc":"Ligne I-II "},
{"href":"lobbes.htm","desc":"Lobbes (14 vues)"},
{"href":"lodelinsart.htm","desc":"Lodelinsart I-II (10 vues)"},
{"href":"lodelinsart_ouest.htm","desc":"Lodelinsart Ouest"},
{"href":"lompret.htm","desc":"Lompret (7 vues)"},
{"href":"luttre.htm","desc":"Luttre (13 vues)"},
{"href":"macon.htm","desc":"Macon"},
{"href":"maffle.htm","desc":"Maffle (2 vues)"},
{"href":"manage_I.htm","desc":"Manage I (3 vues)"},
{"href":"manage_II.htm","desc":"Manage II (11 vues)"},
{"href":"manage_III.htm","desc":"Manage III (14 vues)"},
{"href":"manage_saint_eloi.htm","desc":"Manage Saint Eloi"},
{"href":"marchienne_au_pont.htm","desc":"Marchienne au Pont (14 vues)"},
{"href":"marchienne_est.htm","desc":"Marchienne Est (2 vues)"},
{"href":"marchienne_zone.htm","desc":"Marchienne Zone (10 vues)"},
{"href":"marche_lez_ecaussinnes.htm","desc":"Marche les Ecaussinnes I-II (6 vues)"},
{"href":"marcq.htm","desc":"Marcq (2 vues)"},
{"href":"mariemont.htm","desc":"Mariemont III (4 vues)"},
{"href":"masnuy_saint_pierre.htm","desc":"Masnuy Saint Pierre (3 vues)"},  
{"href":"masses_diarbois.htm","desc":"Masses Diarbois (Ransart) (3)"},
{"href":"maubray.htm","desc":"Maubray (2 vues)"},
{"href":"merbes.htm","desc":"Merbes Ste Marie (3 vues)"},
{"href":"meslin.htm","desc":"Meslin l'Evêque (7 vues/1 plan)"},
{"href":"mevergnies.htm","desc":"Mévergnies Attre (5 vues)"},
{"href":"mignault.htm","desc":"Mignault (5 vues)"},
{"href":"momignies.htm","desc":"Momignies (3 vues)"},
{"href":"monceau_usines.htm","desc":"Monceau Usines (+ 1 plan)"},
{"href":"mons.htm","desc":"Mons I "},
{"href":"mons_I.htm","desc":"Mons II (10 vues)"},
{"href":"mons_II.htm","desc":"Mons III (9 vues)"},
{"href":"mons_III.htm","desc":"Mons IV (2 vues)"},
{"href":"mons_III.htm","desc":"Mons V (7 vues)"},
{"href":"monsville.htm","desc":"Monsville (3 vues)"},
{"href":"montignies_sur_sambre.htm","desc":"Montignies sur Sambre (5 vues)"}, 
{"href":"mont_sur_marchienne.htm","desc":"Mont Sur Marchienne Zone Etat"}, 
{"href":"morlanwelz.htm","desc":"Morlanwelz (27 vues)"},
{"href":"morlanwelz_olive.htm","desc":"Morlanwelz l'Olive (2 vues)"},
{"href":"mouscron.htm","desc":"Mouscron (14 vues)"},
{"href":"naast.htm","desc":"Naast (9 vues)"},
{"href":"nechin.htm","desc":"Nechin"},
{"href":"neufvilles.htm","desc":"Neufvilles (11 vues)"},
{"href":"nimy.htm","desc":"Nimy I-II (12 vues)"},
{"href":"nimy_maisieres.htm","desc":"Nimy Maisières"},
{"href":"obaix.htm","desc":"Obaix Buzet (11 vues)"},
{"href":"obigies.htm","desc":"Obigies (11 vues/1 plan)"},
{"href":"obourg.htm","desc":"Obourg I-II (7 vues)"},
{"href":"ogy.htm","desc":"Ogy (3 vues)"},
{"href":"ollignies.htm","desc":"Ollignies I-II (9 vues/1 plan)"},
{"href":"ormeignies.htm","desc":"Ormeignies (3 vues)"},
{"href":"orroir.htm","desc":"Orroir (10 vues)"},
{"href":"papignies.htm","desc":"Papignies (15 vues/1 plan)"},
{"href":"paturages.htm","desc":"Pâturages (4 vues)"},
{"href":"pecq.htm","desc":"Pecq (2 vues)"},
{"href":"pecq_vicinal.htm","desc":"Pecq vicinale"},
{"href":"peronnes.htm","desc":"Peronnes lez Antoing"},
{"href":"peruwelz.htm","desc":"Peruwelz (10 vues)"},
{"href":"petit_enghien.htm","desc":"Petit Enghien (2 vues)"},
{"href":"pieton.htm","desc":"Piéton I-II (14 vues)"},
{"href":"pipaix.htm","desc":"Pipaix (3 vues)"}, 
{"href":"pottes.htm","desc":"Pottes"},
{"href":"pontacellesnord.htm","desc":"Pont Ã  Celles Nord (9 vues)"}, 
{"href":"pontacellessud.htm","desc":"Pont Ã  Celles Sud"},
{"href":"pont_rouge.htm","desc":"Pont Rouge(3 vues)"},
{"href":"quaregnon.htm","desc":"Quaregnon I-II (12 vues)"},
{"href":"quevaucamps.htm","desc":"Quevaucamps (13 vues)"},
{"href":"quevy.htm","desc":"Quévy (19 vues)"},
{"href":"quievrain.htm","desc":"Quiévrain (34 vues)"},
{"href":"quievrain_vic.htm","desc":"Quiévrain vicinale (9 vues)"},
{"href":"rance.htm","desc":"Rance (2 vues)"},
{"href":"ransart.htm","desc":"Ransart (6 vues)"},
{"href":"rebaix.htm","desc":"Rebaix I-II (14 vues)"},
{"href":"ressaix.htm","desc":"Ressaix (8 vues)"},
{"href":"reves.htm","desc":"Rèves (3 vues)"},
{"href":"riezes.htm","desc":"Riezes"},
{"href":"rigaudrye.htm","desc":"Rigaudrye (2 vues/ 1 plan)"},
{"href":"robechies.htm","desc":"Robechies"},
{"href":"roisin.htm","desc":"Roisin Autreppe (23 V/ 2 PL)"},
{"href":"roisin_2019.htm","desc":"Roisin A. en 2019 (19 vues)"},
{"href":"ronquieres.htm","desc":"Ronquières (9 vues)"},
{"href":"roux.htm","desc":"Roux I-II (11 vues)"},
{"href":"rumes.htm","desc":"Rumes (4 vues)"},
{"href":"russeignies.htm","desc":"Russeignies (5 vues)"}, 
{"href":"saint_amand.htm","desc":"Saint-Amand-lez-Fleurus (+1 plan)"},
{"href":"saint_ghislain.htm","desc":"Saint Ghislain (23 vues)"},
{"href":"sart_les_moines.htm","desc":"Sart-les-Moines (4 vues)"}, 
{"href":"seloignes.htm","desc":"Seloignes Monceau (4 vues)"},
{"href":"seneffe.htm","desc":"Seneffe (12 vues)"},
{"href":"silly.htm","desc":"Silly I-II (10 vues / 1 plan)"},
{"href":"sirault.htm","desc":"Sirault (6 vues)"},
{"href":"sivry.htm","desc":"Sivry (15 vues)"},
{"href":"soignies.htm","desc":"Soignies (21 vues)"},
{"href":"soleilmont.htm","desc":"Soleilmont (1 vue / 1 plan)"},
{"href":"solre_saint_gery.htm","desc":"Solre-Saint-Géry (2 vues)"},
{"href":"solre_sur_sambre.htm","desc":"Solre-sur-Sambre (16 vues)"},
{"href":"stambruges.htm","desc":"Stambruges (9 vues)"},
{"href":"stree.htm","desc":"Strée (8 vues)"},
{"href":"templeuve.htm","desc":"Templeuve I-II (10 vues)"},
{"href":"tertre.htm","desc":"Tertre (15 vues)"}, 
{"href":"tertre_carbo.htm","desc":"Tertre Carbo"},  
{"href":"thieu.htm","desc":"Thieu I-II (6 vues)"},
{"href":"thimeon.htm","desc":"Thiméon (3 vues)"},
{"href":"thuillies.htm","desc":"Thuillies I-II (3 vues)"},
{"href":"thuin_nord.htm","desc":"Thuin Nord (14 vues)"},
{"href":"thuin_ouest.htm","desc":"Thuin Ouest (7 vues/4 bonus)"},
{"href":"thulin.htm","desc":"Thulin (13 vues)"},
{"href":"thumaide.htm","desc":"Thumaide (3 vues)"},
{"href":"tournai_I.htm","desc":"Tournai I"},
{"href":"tournai.htm","desc":"Tournai (16 vues/1 bonus)"},
{"href":"tourpes.htm","desc":"Tourpes (2 vues)"}, 
{"href":"trazegnies.htm","desc":"Trazegnies I-II (14 vues)"},
{"href":"trieu_a_vallee.htm","desc":"Trieu-Ã -Vallée"},
{"href":"vaudignies.htm","desc":"Vaudignies (4 vues)"},
{"href":"vaulx.htm","desc":"Vaulx (6 vues)"}, 
{"href":"vellereille.htm","desc":"Vellereille le Sec (3 vues)"},
{"href":"viesville.htm","desc":"Viesville (10 vues)"},
{"href":"ville_pommeroeul.htm","desc":"Ville Pommeroeul (5 vues)"},
{"href":"villerot.htm","desc":"Villerot"},
{"href":"villers_la_tour.htm","desc":"Villers la tour (3 vues)"},
{"href":"villers_perwin.htm","desc":"Villers Perwin (2 vues)"},
{"href":"villers_poterie.htm","desc":"Villers Poterie (9 vues)"},
{"href":"virelles.htm","desc":"Virelles (8 vues)"},
{"href":"warneton.htm","desc":"Warneton (4 vues)"},
{"href":"warquignies.htm","desc":"Warquignies (2 vues/2 plans)"},
{"href":"warquignies_clinique.htm","desc":"Warquignies clinique (1 vue/2 plans)"},
{"href":"wasmes.htm","desc":"Wasmes (2 vues/1 plan)"},
{"href":"wilbeauroux.htm","desc":"Wilbeauroux (2 vues)"},
{"href":"willemeau.htm","desc":"Willemeau Froidmont (4 vues)"}

];




	const xtractname = (str) => str.includes("/")?
		str.split("/")[1].split(".htm")[0] :
		str.split(".htm")[0];
	if(!slugare) return "";
	slugare = slugare.replaceAll(" ","_");
	const res = garesbelgeslist.filter(x => xtractname(x.href) === slugare);
	if(res.length < 1){
		if(slugare.includes("-")){
			return getGareBelge(slugare.replaceAll("-","_"));
		}
		if(slugare.includes("'")){
			return getGareBelge(slugare.replaceAll("'","_"));
		}
		else return "";
	}
	if(res.length > 1) console.log("getGareBelge", slugare, res.length, JSON.stringify(res));
	else void 0; //console.log("getGareBelge", slugare, res[0].href);
/*if(res.length === 1) void 0; //console.log("getGareBelge of", slugare, xtractname(res[0].href));
else console.log("getGareBelge among", slugare, JSON.stringify(res));*/
	return " gb:[" + res[0].href + "] ";

}
